################################################################################
# GitLab CI is used for multiple purposes
#
# 1. Building and testing of commits to all branches except 'ci_test' and 
#   'coverity_scan' and sending of the ctest results to the CDASH server
#    - these jobs exclude external pull requests and the two branches 
#      'ci_test' and 'coverity_scan' by the rule
#       except:
#       - external_pull_requests
#       - ci_test
#       - coverity_scan
#
# 2. Building and testing of external pull requests (PRs) [to be added]
#
# 3. Building and extensive testing of commits to branch 'ci_test' [to be added]
#
# 4. Coverity scan of commits to branch 'coverity_scan' [to be added]
#
# 5. Test installation and deployment
#
# 6. Building docker images and pushing them to DockerHub
################################################################################

################################################################################
# 1. Building and testing of commits to all branches except 'ci_test' and 
#    'coverity_scan' and sending of the ctest results to the CDASH server
################################################################################

.test:linux:base:
  tags:
    - linux
  stage: test
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/$IMAGE
  variables:
    BUILD_TYPE:             "Release"
    GENERATOR:              "Ninja"
    GISMO_OPTIONAL:       "gsOpennurbs"
    LABELS_FOR_SUBPROJECTS: "'gismo;examples;unittests;doc-snippets'"
    CTEST_ARGS:             ""
  script:
    - apt-get update -y
    - apt-get install g++ cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE="$BUILD_TYPE" -D UPDATE_REPO=ON -D CTEST_CMAKE_GENERATOR="$GENERATOR" -D CNAME=$CNAME -D CXXNAME=$CXXNAME -D CTEST_TEST_TIMEOUT=150 -D GISMO_OPTIONAL="$GISMO_OPTIONAL" -D LABELS_FOR_SUBPROJECTS="$LABELS_FOR_SUBPROJECTS" -D CMAKE_ARGS="$CMAKE_ARGS" $CTEST_ARGS -VV
  interruptible: true
  except:
    - ci_test
    - coverity_scan
    - external_pull_requests
    
#-------------------------------------------------------------------------------
# Clang 8-13, C++11,14,17,20,23
#-------------------------------------------------------------------------------

# Clang 8, C++11, Release
linux_x86_64_clang8_cxx11_release_double_int32t:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:8"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=double;-DGISMO_INDEX_TYPE=int32_t'"

# Clang 9, C++14, Release
linux_x86_64_clang9_cxx14_release_longdouble_int64t:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:9"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=long double;-DGISMO_INDEX_TYPE=int64_t'"
    
# Clang 10, C++17, Release
linux_x86_64_clang10_cxx17_release_mpreal_long:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:10"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpfr::mpreal;-DGISMO_INDEX_TYPE=long'"

# Clang 11, C++20, Release
linux_x86_64_clang11_cxx20_release_mpq_long:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:11"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpq_class;-DGISMO_INDEX_TYPE=long'"
    CTEST_ARGS:       "-D DO_TESTS=FALSE"

# Clang 13 (latest), C++23, Release  (works!!!!)
linux_x86_64_clang13_cxx23_release_float_int:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:latest"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=23;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=float;-DGISMO_INDEX_TYPE=int'"
    GISMO_OPTIONAL: "gsOpennurbs\\;"

#-------------------------------------------------------------------------------
# GCC 8-12, C++11,14,17,20
#-------------------------------------------------------------------------------
    
# GCC 8, C++11, Release
linux_x86_64_gcc8_cxx11_release_mpreal_long:
  extends: .test:linux:base
  variables:
    IMAGE:            "gcc:8"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpfr::mpreal;-DGISMO_INDEX_TYPE=long'"

# GCC 9, C++14, Release
linux_x86_64_gcc9_cxx14_release_longdouble_int64t:
  extends: .test:linux:base
  variables:
    IMAGE:            "gcc:9"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=long double;-DGISMO_INDEX_TYPE=int64_t'"
    
# GCC 10, C++17, Release
linux_x86_64_gcc10_cxx17_release_double_int32t:
  extends: .test:linux:base
  variables:
    IMAGE:            "gcc:10"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=double;-DGISMO_INDEX_TYPE=int32_t'"
    GISMO_OPTIONAL: "gsOpennurbs\\;"

# GCC 11, C++20, Release
linux_x86_64_gcc11_cxx20_release_float_int:
  extends: .test:linux:base
  variables:
    IMAGE:            "gcc:11"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=float;-DGISMO_INDEX_TYPE=int'"
    
# GCC 12 (latest), C++23, Release
linux_x86_64_gcc12_cxx23_release_float_int:
  extends: .test:linux:base
  variables:
    IMAGE:            "gcc:latest"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=float;-DGISMO_INDEX_TYPE=int'"
    CTEST_ARGS:       "-D DO_TESTS=FALSE"    
    GISMO_OPTIONAL: "gsOpennurbs\\;gsSpectra"
    
################################################################################
# 2. Building and testing of external pull requests (PRs)
################################################################################

# Clang 10, C++17, Release
linux_x86_64_clang10_cxx17_release_mpreal_long:
  extends: .test:linux:base
  variables:
    IMAGE:            "silkeh/clang:10"
    CNAME:            "clang"
    CXXNAME:          "clang++"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpfr::mpreal;-DGISMO_INDEX_TYPE=long'"
  except:
    - ci_test
    - coverity_scan

# GCC 10, C++14, Release
linux_x86_64_gcc10_cxx14_release_mpq_long:
  extends: .test:linux:base
  after_script:
    - cat /builds/gismo-ci/build_ExperimentalRelease_g++/gmp-prefix/src/gmp-stamp/gmp-configure
  variables:
    IMAGE:            "gcc:10"
    CNAME:            "gcc"
    CXXNAME:          "g++"
    GENERATOR:        "Unix Makefiles"
    CMAKE_ARGS:       "'-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpq_class;-DGISMO_INDEX_TYPE=int64_t'"    
  except:
    - ci_test
    - coverity_scan   
    
################################################################################
# 3. Building and extensive testing of commits to branch 'ci_test'
################################################################################

################################################################################
# 4. Coverity scan of commits to branch 'coverity_scan'
################################################################################

################################################################################
# 5. Test installation and deployment
################################################################################

# Standard installation and deployment on linux
install_and_deploy_linux:
  tags:
    - linux
  stage: test #deploy #(deploy will only run only when all test succeeds)
  image: gcc:9
  script:
    - apt-get update -y
    - apt-get g++ install cmake -y
    - export MAKEFLAGS=-j3
    - rm -rf ~/.cmake /builds/gismo-ci/buildlib/CMakeCache.txt /builds/gismo-ci/buildlib/lib /usr/lib*/gismo /usr/lib*/*gismo*.* /usr/include/gismo /usr/share/gismodata /builds/gismo-ci/buildproj # Cleanup folders
    - if [ ! -d "/builds/gismo-ci/buildlib" ]; then mkdir /builds/gismo-ci/buildlib; fi
    - cd /builds/gismo-ci/buildlib
    - cmake ../gismo -DBUILDNAME="$CI_JOB_NAME" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-[gitlab-ci]" -D CMAKE_GENERATOR="Unix Makefiles" -D CMAKE_INSTALL_PREFIX=/usr -DTARGET_ARCHITECTURE=generic #-D GISMO_OPTIONAL="gsOpennurbs\\;gsIpOpt\\;gsSpectra"
    - cmake --build . --target gismo #--parallel 3
    # I. Test deploy from build tree
    - cp /builds/gismo-ci/gismo/CTestConfig.cmake /builds/gismo-ci/gismo/deploy/
    - mv /builds/gismo-ci/gismo/examples/*.cpp /builds/gismo-ci/gismo/deploy/
    - mkdir /builds/gismo-ci/buildproj; cd /builds/gismo-ci/buildproj
    - cmake ../gismo/deploy -Dgismo_DIR=/builds/gismo-ci/buildlib -DBUILDNAME="$CI_JOB_NAME-local" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CMAKE_GENERATOR="Unix Makefiles" || true
    - ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit
    # II. Test deploy from system tree
    - cd /builds/gismo-ci/buildlib
    - cmake --build . --target install
    - rm -rf ~/.cmake /builds/gismo-ci/buildproj
    - mkdir /builds/gismo-ci/buildproj; cd /builds/gismo-ci/buildproj
    - cmake ../gismo/deploy -DBUILDNAME="$CI_JOB_NAME-system" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CMAKE_GENERATOR="Unix Makefiles" || true
    - ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest
    # III. Test direct use of -lgismo
    - rm -rf ./poisson_example.out
    - g++ -v /builds/gismo-ci/gismo/deploy/poisson_example.cpp -o poisson_example.out -I/usr/include/gismo -lgismo 2> compile.log
    - ctest --output-on-failure -A compile.log -M Experimental -T Submit
    - if [ ! -f "poisson_example.out" ]; then cat compile.log; fi
    - ./poisson_example.out
  only:
    - stable
    - external_pull_requests

