stages:
  - compile
  - test
  - doc

.linux-gcc:
  only:
    - ci
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16

.linux-intel:
  before_script:
    - source /opt/intel/oneapi/compiler/latest/env/vars.sh
  variables:
    GIT_CLEAN_FLAGS: none
  only:
    - ci
  tags:
    - CentOS-gs

.windows:
  only:
    - ci
  tags:
    - windows-gs

.macos-clang:
  only:
    - ci
  tags:
    - macos-gs

compile-intel:
  extends: .linux-intel
  stage: compile
  before_script:
    - export CC=icx
    - export CXX=icpx
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="CentOS_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=15 -D CTEST_BINARY_DIRECTORY=./build -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D CTEST_BUILD_NAME="Intel-ICC_$CI_COMMIT_SHORT_SHA" -D DO_TESTS=FALSE #-D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" #-VV

test-intel:
  extends: .linux-intel
  needs:
    - compile-intel
  stage: test
  script:
    - ctest -D ExperimentalTest -D ExperimentalSubmit

doc:
  extends: .linux-intel
  stage: doc
  interruptible: false
  needs:
    - compile-intel
  script:
    - cd build
    - cmake --build . --target doc    -
    - ctest --add-notes doc/doxygen.log -M Experimental -T Submit
    - cd doc/html
    - rm -rf .git
    - git init -b master
    - git config user.email "doc@gismo.ci"
    - git config user.name "doc-ci"
    - git add .
    - git commit --quiet -m "G+Smo doc"
    - git push --force --quiet https://$GITHUB@github.com/gismo/gismo.github.io.git master:master

compile-test-msvc:
  extends: .windows
  stage: compile
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="Windows_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Visual Studio 17 2022" -D CTEST_BUILD_JOBS=10 -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D CTEST_BUILD_NAME="VS_17_2022_%CI_COMMIT_SHORT_SHA%" #-D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS"#-VV

compile-macos:
  extends: .macos-clang
  stage: compile
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="MacOS_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=15 -D CTEST_BUILD_NAME="OSX-ICC_$CI_COMMIT_SHORT_SHA" -D DO_TESTS=TRUE -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" #-VV
