#https://gitlab.inria.fr/gitlabci_gallery/windows/windows-10

stages: ["G+Smo"]

test:
  stage: "G+Smo"
  interruptible: true
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    -  apk add --update doxygen g++ cmake ninja git
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="inria-shared" -D CTEST_CMAKE_GENERATOR="Ninja" -D CTEST_BUILD_JOBS=4 -D CTEST_BINARY_DIRECTORY=./build -D CTEST_CONFIGURATION_TYPE=Release -D CMAKE_ARGS="'-DGISMO_BUILD_UNITTESTS=ON;TARGET_ARCHITECTURE=none'" ##-VV
    #- cmake --build ./build --target doc
    - cd ./build/doc; ls index.html

doc:
  stage: "G+Smo"
  needs:  # Defined a "needs" relationship with job1
    - test
  interruptible: false
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    -  apk add --update doxygen g++ cmake ninja git
  script:
    - pwd
    - cmake --build ./build --target doc
    - cd ./build/doc; ls index.html

#    - rm -rf .git
#    - git init
#    - git config user.email "doc@gismo.ci"
#    - git config user.name "doc-ci"
#    - git add .
#    - git commit --quiet -m "G+Smo doc"
#    - git push --force --quiet https://oauth2:$GITHUB@github.com/gismo/gismo.github.io.git master:master
