#https://gitlab.inria.fr/gitlabci_gallery/windows/windows-10

stages: ["G+Smo", "G+Smo-doc"]

job1:
  stage: "G+Smo"
  #interruptible: true
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    -  apk add --update doxygen g++ cmake ninja git
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_CMAKE_GENERATOR="Ninja" -D CTEST_BUILD_JOBS=4 -D CTEST_BINARY_DIRECTORY=./build -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo ##-VV

# Deploy the documentation on the main branch
pages:
  stage: "G+Smo-doc"
  #interruptible: true
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  #rules:
  #  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add --update doxygen
  script:
    - pwd
    - cmake --build ./build --target doc
    - cd ./build/doc; ls index.html
#  artifacts:
#    when: always
#    paths:
#      - public
