stages:
  - compile
  - doc
  #- test

.linux-gcc:
  only:
    - ci
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16

.linux-intel:
  only:
    - ci
  tags:
    - CentOS

.windows:
  only:
    - ci
  tags:
    - windows-gsx

.macos-clang:
  only:
    - ci
  tags:
    - macos

compile-intel:
  extends: .linux-intel
  stage: compile
  interruptible: true
  #before_script:
  #  -  apk add --update cmake git g++ doxygen graphviz make
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="shared_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=4 -D CTEST_BINARY_DIRECTORY=./build -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D CTEST_BUILD_NAME="Intel-ICC_$CI_COMMIT_SHORT_SHA" -D DO_TESTS=FALSE #-D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS"#-VV

doc:
  extends: .linux-intel
  stage: doc
  interruptible: false
  needs:
    - compile-intel
  script:
    - cmake --build ./build --target doc
    - ctest --add-notes doc/doxygen.log -M Experimental -T Submit
    - cd build/doc/html
    - rm -rf .git
    - git init -b master
    - git config user.email "doc@gismo.ci"
    - git config user.name "doc-ci"
    - git add .
    - git commit --quiet -m "G+Smo doc"
    - git push --force --quiet https://$GITHUB@github.com/gismo/gismo.github.io.git master:master

compile-test-msvc:
  extends: .windows
  stage: compile
  interruptible: true
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="shared_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Visual Studio 17 2022" -D CTEST_BUILD_JOBS=10 -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D CTEST_BUILD_NAME="Windows_VS_17_2022_$CI_COMMIT_SHORT_SHA" #-D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS"#-VV
