#https://gitlab.inria.fr/gitlabci_gallery/windows/windows-10

stages: ["G+Smo 1"]

test1:
  stage: "G+Smo 1"
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ls
    - pwd
    - ctest -S cmake/ctest_script.cmake
