#https://gitlab.inria.fr/gitlabci_gallery/windows/windows-10

stages: ["G+Smo"]

test+doc:
  stage: "G+Smo"
  interruptible: true
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    -  apk add --update cmake git g++ doxygen graphviz ninja #make
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="inria-shared" -D CTEST_CMAKE_GENERATOR="Ninja" -D CTEST_BUILD_JOBS=4 -D CTEST_BINARY_DIRECTORY=./build -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" #-VV
    - cmake --build ./build --target doc
    - cd build/doc/html
    #- rm -rf .git
    #- git config --global init.defaultBranch master
    - git init -b master
    - git config user.email "doc@gismo.ci"
    - git config user.name "doc-ci"
    - git add .
    - git commit --quiet -m "G+Smo doc"
    - git push --force --quiet https://$GITHUB@github.com/gismo/gismo.github.io.git master:master
