#https://gitlab.inria.fr/gitlabci_gallery/windows/windows-10

stages: ["G+Smo 1"]

test1:
  stage: "G+Smo 1"
  interruptible: true
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16
  before_script:
    -  apk add --update doxygen g++ cmake ninja git
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_CMAKE_GENERATOR="Ninja" -VV


# Deploy the documentation on the main branch
#pages:
#  stage: G+Smo-doc
#  interruptible: true
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#  dependencies: []
#  before_script:
#    - apk add --update doxygen
#  script:
#    - doxygen
#  artifacts:
#    when: always
#    paths:
#      - public
