// Jenkins script for G+Smo, Angelos Mantzaflaris, 2019

// Gather builders
def labels = ['gismo-ubuntu', 'gismo-macos', 'gismo-fedora', 'gismo-win7x64']
def builders = [:]
for (x in labels)
{
    def label = x
    builders[label] =
    {
        node(label)
	{
	    checkout scm
	    buildGismo()
	}
    }
}

// Start all builders
parallel builders

// Building G+Smo
void buildGismo()
{
    dir('build')
    {
	//cmd ctest -S ../cmake/ctest_script.cmake -D PROJECT_NAME=Gismo -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;gismo_dev;example_dev;unittest_dev;motor' -D CTEST_TEST_MODEL=Nightly -D GISMO_SUBMODULES='unsupported;motor' CMAKE_ARGS='-DGISMO_BUILD_UNITTESTS=ON' -Q

        cmd 'cmake ../ -DGISMO_BUILD_UNITTESTS=ON'
	//-DSITE=
        cmd 'ctest --output-on-failure -C RelWithDebinfo -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit'
    }
}

// Cross-platform cmd
def cmd (acmd)
{
    if (isUnix()) { sh acmd } else { bat acmd}
}
