// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#pragma once

#include <dtkCore/dtkPlugin.h>

#include "gsAxelPluginExport.h"

#include <gismo.h>

class dtkAbstractDataFactory;
class dtkAbstractProcessFactory;

class gsAxelPluginPrivate;

class GSAXELPLUGIN_EXPORT gsAxelPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)
    
public:
    gsAxelPlugin(QObject *parent = 0);
    ~gsAxelPlugin(void);
    
    virtual bool initialize(void);
    virtual bool uninitialize(void);
    
    virtual QString name(void) const;
    virtual QString description(void) const;
    
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;
    
public:
    static dtkAbstractDataFactory *dataFactSingleton;
    static dtkAbstractProcessFactory *processFactSingleton;
    
    
private:
    gsAxelPluginPrivate *d;
};

