// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTDATADIALOG_H
#define MYPLUGINDEFAULTDATADIALOG_H

#include <axlGui/axlInspectorObjectFactory.h>
#include <axlGui/axlInspectorToolFactory.h>

#include "gsAxelPluginExport.h"


class dtkAbstractData;

class gsGeometryDialogPrivate;

class GSAXELPLUGIN_EXPORT gsGeometryDialog : public axlInspectorObjectInterface
{
    Q_OBJECT
    
public:
    gsGeometryDialog(QWidget *parent = 0);
    ~gsGeometryDialog(void);
    
    QSize sizeHint(void) const;
    
    static bool registered(void);

signals:
    
    void colorChanged(QColor color,  dtkAbstractData *data);
    
    void dataChangedByShader(dtkAbstractData *data, QString isophoteShaderXml);
    void dataChangedByOpacity(dtkAbstractData *data, double opacity);
    
    void dataChangedByColor(dtkAbstractData *data, double red, double green, double blue);
    void dataChangedByGeometry(dtkAbstractData *data);
    
    void update(void);

    void dataInserted(axlAbstractData* data);
    
public slots:
    void setData(dtkAbstractData *data);
    
    void onColorChanged(QColor color);
    void onOpacityChanged(int opacity);
    
    void onSamplingDataChanged_u(int numSamples);
    void onSamplingDataChanged_v(int numSamples);
    void onSamplingDataChanged_w(int numSamples);

    void onControlPointChanged_x(double c);
    void onControlPointChanged_y(double c);
    void onControlPointChanged_z(double c);

    void onControlPointIndexChanged(int i);
    void onIndexSelected(int i);

    void openShader(void);
    void onShaderStateChanged(bool isShader);
    void onShaderChanged(QString);
    void onLineEditShaderChanged(QString);
    
    void showBasis(void);

    void saveGeometry(void);

    void refineGeometry(void);

    void insertKnot(void);

    /* Joker
    void jokerPlay(void);
    //*/

    // void onShowCurrentPoint(double u, double v);
    // void onMoveCurrentPoint(double u, double v);
    // void onHideCurrentPoint(double u, double v);

private :
    void updateText();

    void initComboBoxShaderValue(void);
    void initWidget(void);
    int initOpacityValue(void);
    QString initShaderValue(void);
    QColor initColorValue(void);
    
    gsGeometryDialogPrivate *d;
};

axlInspectorObjectInterface *creategsGeometryDialog(void);


#endif // MYPLUGINDEFAULTDATADIALOG_H

