// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */
#ifndef MYPLUGINDEFAULTPROCESS_H
#define MYPLUGINDEFAULTPROCESS_H

#include "MyPluginPluginExport.h"

#include <dtkCore/dtkAbstractProcess.h>

class axlAbstractData;

class MyPluginDefaultProcessPrivate;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultProcess: public dtkAbstractProcess
{
    Q_OBJECT
    
public:
    MyPluginDefaultProcess(void);
    virtual ~MyPluginDefaultProcess(void);
    
    virtual QString description(void) const;
    virtual QString identifier(void) const;
    
    
public:
    static bool registered(void);
    
public:
    dtkAbstractData *output(void);
    
public slots:
    void setInput(dtkAbstractData *data, int channel);
    
public slots:
    int update(void);
    
private:
    MyPluginDefaultProcessPrivate *d;
};

dtkAbstractProcess *createMyPluginDefaultProcess(void);

#endif //MYPLUGINDEFAULTPROCESS_H

