// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTPROCESSDIALOG_H
#define MYPLUGINDEFAULTPROCESSDIALOG_H

#include "MyPluginPluginExport.h"

#include <axlGui/axlInspectorToolFactory.h>


class axlAbstractData;

class MyPluginDefaultProcessDialogPrivate;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultProcessDialog : public axlInspectorToolInterface
{
    Q_OBJECT
    
public:
    MyPluginDefaultProcessDialog(QWidget *parent = 0);
    ~MyPluginDefaultProcessDialog(void);
    
    static bool registered(void);
    
signals:
    void dataInserted(axlAbstractData *data);
    
    
public slots:
    void run(void);
    
private:
    MyPluginDefaultProcessDialogPrivate *d;
};

axlInspectorToolInterface *createMyPluginDefaultProcessDialogPrivate(void);


#endif //MYPLUGINDEFAULTPROCESSDIALOG_H

