[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.16",
    "pybind11",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python3 {project}/python_examples/bspline_curve_example.py"
