#!/bin/bash
# hooks/_compiler_settings

# Compiler setting
shopt -s extglob;
case "$IMAGE_NAME" in

    # Clang
    
    ?(*\-)clang3.5?(\-*))
        CC=clang-3.5
        CXX=clang++-3.5
        ;;
    ?(*\-)clang3.6?(\-*))
        CC=clang-3.6
        CXX=clang++-3.6
        ;;
    ?(*\-)clang3.7?(\-*))
        CC=clang-3.7
        CXX=clang++-3.7
        ;;
    ?(*\-)clang3.8?(\-*))
        CC=clang-3.8
        CXX=clang++-3.8
        ;;
    ?(*\-)clang3.9?(\-*))
        CC=clang-3.9
        CXX=clang++-3.9
        ;;
    ?(*\-)clang4.0?(\-*))
        CC=clang-4.0
        CXX=clang++-4.0
        ;;
    ?(*\-)clang5.0?(\-*))
        CC=clang-5.0
        CXX=clang++-5.0
        ;;
    ?(*\-)clang6.0?(\-*))
        CC=clang-6.0
        CXX=clang++-6.0
        ;;
    ?(*\-)clang7?(\-*))
        CC=clang-7
        CXX=clang++-7
        ;;
    ?(*\-)clang8?(\-*))
        CC=clang-8
        CXX=clang++-8
        ;;

    # GCC
                       
    ?(*\-)gcc4.7?(\-*))
        CC=gcc-4.7
        CXX=g++-4.7
        FC=gfortran-4.7
        ;;
    ?(*\-)gcc4.8?(\-*))
        CC=gcc-4.8
        CXX=g++-4.8
        FC=gfortran-4.8
        ;;
    ?(*\-)gcc4.9?(\-*))
        CC=gcc-4.9
        CXX=g++-4.9
        FC=gfortran-4.9
        ;;
    ?(*\-)gcc5?(\-*))
        CC=gcc-5
        CXX=g++-5
        FC=gfortran-5
        ;;

    *)
        echo "[***] Unsupported compiler"
        exit 1
        ;;
esac
shopt -u extglob;

echo "[---] CC:                     ${CC}"
echo "[---] CXX:                    ${CXX}"
echo "[---] FC:                     ${FC}"
