/** @file gsOptimModuleEntry.cpp

    @brief C-linkage entry points of the gsOptim runtime module.

    Compiled only when GISMO_BUILD_MODULE_LIB=ON. Provides the two
    symbols gsModuleManager expects:

      gismo_module_info()     - ABI handshake (see gsModuleInfo.h)
      gismo_module_register() - populates the optimizer registry

    The static registrar in gsOptimRegister.cpp already fires when the
    module library is loaded; gismo_module_register() repeats the calls,
    which is safe because registration is idempotent.

    This file is part of the G+Smo library.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Author(s): H.M. Verhelst
*/

#include <gsCore/gsExport.h>
#include <gsModules/gsModuleInfo.h>

#include "gsOptimModuleVersion.h" // generated by gismo_add_module_lib

namespace gismo { GISMO_EXPORT void gsOptimRegisterAll(); }

static const gismo::gismo_module_info_t s_info = {
    GISMO_MODULE_ABI_VERSION_MAJOR,
    GISMO_MODULE_ABI_VERSION_MINOR,
    GISMO_MODULE_NAME,
    GISMO_MODULE_VERSION,
    GISMO_MODULE_COEFF_TYPE,
    GISMO_MODULE_INDEX_TYPE,
    {}
};

extern "C" GISMO_EXPORT
const gismo::gismo_module_info_t * gismo_module_info()
{ return &s_info; }

extern "C" GISMO_EXPORT
void gismo_module_register()
{ gismo::gsOptimRegisterAll(); }
