/** @file gsOptimModuleEntry.cpp

    @brief C-linkage entry points for the gsOptim MODULE shared library.

    This file is part of the G+Smo library.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Author(s): H.M. Verhelst

    This file is compiled only when GISMO_BUILD_MODULE_LIB=ON.
    It provides the two mandatory C-linkage symbols that gsModuleLoader
    expects to find in every gismo MODULE .so:

      gismo_module_info()     — version handshake struct
      gismo_module_register() — explicit registration trigger (belt-and-suspenders)

    The anonymous-namespace static registrar defined inside gsOptim.h already
    fires automatically when the .so is loaded (via .init_array / _init), so
    gismo_module_register() just repeats the calls.  Because
    gsOptimizerRegistry::register_() is idempotent, calling it twice is safe.
*/

#include <gsCore/gsExport.h>
#include <gsModules/gsModuleInfo.h>
#include <gsOptim/gsOptim.h>          // pulls in the static registrar struct

// Per-module version header generated by cmake/gsModule.cmake:
#include "gsOptimModuleVersion.h"

using namespace gismo;

// ---------------------------------------------------------------------------
// Static version info returned by gismo_module_info()
// ---------------------------------------------------------------------------
static const gismo_module_info_t s_gsOptim_info = {
    GISMO_MODULE_ABI_VERSION_MAJOR,
    GISMO_MODULE_ABI_VERSION_MINOR,
    GISMO_MODULE_NAME,       // "gsOptim"
    GISMO_MODULE_VERSION,    // e.g. "1.0.0"
    GISMO_MODULE_COEFF_TYPE, // e.g. "double"
    GISMO_MODULE_INDEX_TYPE, // e.g. "int"
    {}                       // reserved — zero-initialized
};

// ---------------------------------------------------------------------------
// Entry point 1: version handshake
// ---------------------------------------------------------------------------
extern "C" GISMO_EXPORT
const gismo_module_info_t* gismo_module_info()
{
    return &s_gsOptim_info;
}

// ---------------------------------------------------------------------------
// Entry point 2: explicit registration (idempotent)
// ---------------------------------------------------------------------------
extern "C" GISMO_EXPORT
void gismo_module_register()
{
    gsOptimizerRegistry::register_("gsOptim-BFGS", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimBFGS<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-LBFGS", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimLBFGS<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-CG", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimCG<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-GD", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimGD<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-NM", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimNM<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-DE", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimDE<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-DEPRMM", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimDEPRMM<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-PSO", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimPSO<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-PSODV", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimPSODV<real_t>());
    });
    gsOptimizerRegistry::register_("gsOptim-SUMT", []() {
        return gsOptimizer<real_t>::uPtr(new gsOptimSUMT<real_t>());
    });
}
