/** @file reproduce_transient_sphere.cpp

    @brief Transient heat equation with a MOVING sharp front on the EXACT
           spherical patch (Sec.4.3 / Fig.10 geometry), backward Euler, comparing
           r-adaptivity (ALE on a fixed mesh) against uniform, THB, and rh.

    Surface heat equation  du/dt - Lap_S(u) = f  on the sphere patch, manufactured
    EXPANDING RING (annulus) in colatitude
        u(x,t) = sech^2( (vartheta - c(t))/tw ),     vartheta = colatitude,
        c(t)   = c0 + (c1-c0) t/T   (the ring sweeps outward in colatitude),
    with f = du/dt - Lap_S(u) (both analytic, generated and validated by
    scripts/derive_surface_rhs.py) and u imposed as a time-dependent Dirichlet
    datum. Lap_S is the Laplace-Beltrami of Sec.4.3.

    The ring is a BAND, not a step: it decays to 0 on both sides of the circle
    vartheta = c(t) and peaks at 1 on it. It therefore carries its signal in its
    VALUE, so the relocation monitor is ValueBased and the THB/rh arms mark on
    u_ex -- unlike a tanh front, whose signal is entirely in its gradient.

    r-adaptivity: ALE backward Euler on a FIXED analysis basis whose composed
    geometry G = S o sigma is relocated to track the band each step (warm-started).
    Because the basis is fixed, the previous coefficient field carries over with no
    inter-mesh projection; the mesh motion enters through the PHYSICAL mesh velocity
        w(xi) = ( S(sigma_new(xi)) - S(sigma_prev(xi)) ) / Dt   in R^3,
    a tangential surface velocity (this is the surface analogue of the planar
    reproduce_transient_moving.cpp, where w reduced to Dsigma/Dt).

    Usage:
        reproduce_transient_sphere -i <sphere_patch.xml> [-t 0.05] [-K 20] [-N 24]
                                   [--c0 0.35] [--c1 0.7] [--Kreloc 1] [--thbPass 4]

    This file is part of the G+Smo library.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Author(s): Ye Ji (y.ji-1@tudelft.nl)
*/

#include <gismo.h>
#include <gsNurbs/gsSquareDomain.h>
#include <gsOptim/gsOptim.h>
#include <gsHLBFGS/gsHLBFGS.h>
#include <gsAssembler/gsAdaptiveParametrization.h>

using namespace gismo;

static const std::string VSTR = "atan2(sqrt(x^2+y^2),z)";   // colatitude vartheta
static std::string g_t="0.05", g_c="0.35", g_cdot="0.35";

// The moving feature is an expanding RING (annulus), not a filled cap:
//
//     u(vartheta,t) = sech^2( (vartheta - c(t))/t_w ),
//
// i.e. the sech^2 band of half-width t_w centred on the colatitude circle
// vartheta = c(t), which sweeps from c0 to c1.  A tanh front (the previous
// solution here) is ~2 over the whole polar cap and 0 outside it, so it
// carries its signal in its GRADIENT; the ring carries its signal in its
// VALUE.  That is why the relocation monitor below is ValueBased and the
// THB arms mark on u_ex rather than on ||grad_S u_ex||: the two choices are
// one decision, and changing either alone tracks the wrong feature.
//
// GENERATED by  python3 scripts/derive_surface_rhs.py  (--profile ring).
// Placeholders: QVQ colatitude, QWQ radius^2, QCQ c(t), QTQ t_w, QDQ dc/dt.
// Both derivatives in f = du/dt - Lap_S u come from sympy, and that script's
// check suite re-derives these two literals and fails if they no longer
// match, so the source cannot silently drift away from the solution -- a
// drifted source makes the error stagnate instead of converge and is not
// visible by inspection.  DO NOT EDIT BY HAND; edit the script and re-run it.
static const std::string RING_U_TMPL = "1 - tanh(QCQ/QTQ - QVQ/QTQ)^2";
static const std::string RING_F_TMPL = "QDQ*(-2*tanh(QCQ/QTQ - QVQ/QTQ)/QTQ + 2*tanh(QCQ/QTQ - QVQ/QTQ)^3/QTQ) + 2/(QTQ^2*QWQ) - 8*tanh(QCQ/QTQ - QVQ/QTQ)^2/(QTQ^2*QWQ) + 6*tanh(QCQ/QTQ - QVQ/QTQ)^4/(QTQ^2*QWQ) - 2*cos(QVQ)*tanh(QCQ/QTQ - QVQ/QTQ)/(QTQ*QWQ*sin(QVQ)) + 2*tanh(QCQ/QTQ - QVQ/QTQ)^3*cos(QVQ)/(QTQ*QWQ*sin(QVQ))";

/// Replaces every occurrence of \a tok in \a s by \a val.
static std::string subst(std::string s, const std::string& tok, const std::string& val)
{
    for (size_t i=s.find(tok); i!=std::string::npos; i=s.find(tok,i+val.size()))
        s.replace(i, tok.size(), val);
    return s;
}

// Instantiates a generated template at the current band centre/width/speed.
// Every value is wrapped in parentheses: the templates use the placeholders as
// factors (QTQ^2, QCQ/QTQ), so a bare "1e-2" would reassociate.
static std::string fillTmpl(const std::string& tmpl)
{
    std::string s = subst(tmpl, "QVQ", "("+VSTR+")");
    s = subst(s, "QWQ", "(x^2+y^2+z^2)");              // radius^2 (=ww^2)
    s = subst(s, "QCQ", "("+g_c+")");
    s = subst(s, "QTQ", "("+g_t+")");
    s = subst(s, "QDQ", "("+g_cdot+")");
    return s;
}
static std::string exactStr(){ return fillTmpl(RING_U_TMPL); }
static std::string fStr()    { return fillTmpl(RING_F_TMPL); }
static real_t g_quA = 2.0;
static bool   g_hlbfgs = true;   // R-step backend; see relocateFrom()

// Physical mesh velocity w(xi) = (G_new(xi) - G_prev(xi))/Dt in R^3, G = S o sigma.
class MeshVel : public gsFunction<real_t>
{
    const gsGeometry<real_t>& m_Gnew;
    const gsGeometry<real_t>& m_Gprev;
    real_t m_Dt;
public:
    MeshVel(const gsGeometry<real_t>& Gnew, const gsGeometry<real_t>& Gprev, real_t Dt)
        : m_Gnew(Gnew), m_Gprev(Gprev), m_Dt(Dt) {}
    GISMO_CLONE_FUNCTION(MeshVel)
    short_t domainDim() const { return 2; }
    short_t targetDim() const { return 3; }
    void eval_into(const gsMatrix<real_t>& u, gsMatrix<real_t>& res) const
    {
        gsMatrix<real_t> a,b; m_Gnew.eval_into(u,a); m_Gprev.eval_into(u,b);
        res = (a-b)/m_Dt;
    }
};

static gsGeometry<real_t>::uPtr makeIdentity(index_t d, index_t N)
{
    gsGeometry<>::uPtr comp = gsNurbsCreator<>::BSplineSquareDeg(d);
    const index_t nref=(index_t)std::round(std::log2((double)N));
    for (index_t r=0;r<nref;++r) comp->uniformRefine();
    return comp;
}

// Minimum det(J_sigma) sampled on a uniform grid: sigma here is a plain
// gsGeometry (not a gsSquareDomain), which has no minJacobian() accessor.
static real_t sampleMinDetJ(const gsGeometry<real_t>& sigma, index_t nPerDir=9)
{
    gsMatrix<real_t> pts(2, nPerDir*nPerDir);
    index_t c=0;
    for (index_t i=0;i<nPerDir;++i)
        for (index_t j=0;j<nPerDir;++j, ++c)
            pts(0,c)=real_t(i)/(nPerDir-1), pts(1,c)=real_t(j)/(nPerDir-1);
    real_t minDet = std::numeric_limits<real_t>::infinity();
    gsMatrix<real_t> jac;
    for (index_t c2=0;c2<pts.cols();++c2)
    {
        sigma.jacobian_into(pts.col(c2), jac);
        minDet = math::min(minDet, jac.determinant());
    }
    return minDet;
}

// Relocate sigma to track the current ring (VALUE monitor, fixed boundary).
//
// The monitor is 1 + theta*f with f = u_ex.  Because the ring is bounded by 1
// (against |grad_S u| ~ 2/t_w = 40 for the old front), theta must be O(1) here
// where the front wanted 1e-2: at theta=1e-2 the monitor is 1.01, essentially
// flat, and relocation returns an almost-identity sigma.  See the g_stalled
// diagnostic below, which distinguishes that from an optimizer stall.
//
// The ValueBased precondition 1 + theta*f > 0 holds for any theta >= 0 since
// u_ring = sech^2(.) >= 0 (gsAdaptiveParametrization.h, gsOptMesh \pre).
//
// \a maxDisp, if given, receives the largest control displacement from \a init,
// which is 0 exactly when sigma did not move.
static gsGeometry<real_t>::uPtr relocateFrom(const gsGeometry<real_t>& init, const gsGeometry<real_t>& S,
                                             real_t smoothing, real_t penalty, index_t maxIt,
                                             real_t* maxDisp=nullptr)
{
    gsGeometry<>::uPtr comp = init.clone();
    gsSquareDomain<real_t> dom(*comp);
    dom.options().addSwitch("Slide","",false); dom.applyOptions();   // fixed boundary (Sec.4.3)
    if (dom.nControls()>0)
    {
        gsFunctionExpr<> indicator(exactStr(), S.targetDim());
        // gsOptim's L-BFGS has been observed to stall silently on this
        // objective -- sigma left at the identity while convergence is
        // reported -- which is why the schedule study switched to HLBFGS
        // (Results_schedule_study/README.md). Both are reachable so that an
        // optimizer stall stays separable from a too-weak monitor.
        std::unique_ptr<gsOptimizer<real_t> > opt;
        if (g_hlbfgs) opt.reset(new gsHLBFGS<real_t>());
        else           opt.reset(new gsOptim<real_t>::LBFGS());
        opt->options().setInt("MaxIterations",maxIt);
        gsAdaptiveParametrization<real_t,MonitorMode::ValueBased> relo(dom,S,indicator,*opt,false);
        relo.options().setReal("Smoothing",smoothing); relo.options().setReal("Penalty",penalty);
        relo.solve();
        const real_t mJ = relo.computeMinJacobian();
        GISMO_ENSURE(math::isfinite(mJ)&&mJ>0, "reloc folded (minJ="<<mJ<<")");
    }
    gsGeometry<>::uPtr out = dom.domain().clone();
    if (maxDisp)
        *maxDisp = (out->coefs()-init.coefs()).cwiseAbs().maxCoeff();
    return out;
}

// A relocation that leaves sigma at the identity is the failure mode BOTH known
// hazards here produce: a too-weak monitor (theta too small for a ValueBased
// ring) and a silent optimizer stall. It reports a converged solve and an
// r-gain of exactly 1.00x, so without this it reads as a result rather than as
// a non-run. The threshold is one part in 1e4 of the unit parametric domain --
// far below any relocation that tracks a t_w ~ 0.05 ring, far above round-off.
static void warnIfStalled(real_t maxDisp, index_t step)
{
    if (maxDisp < 1e-4)
        gsWarn<<"relocation stalled at step "<<step<<": sigma moved by "<<maxDisp
              <<" (identity). Raise --smoothing (theta) or check the R-step "
              <<"optimizer; do NOT report this as an r result.\n";
}

// One backward-Euler (ALE) step on the surface. wFun != null -> moving mesh.
static void aleStep(const gsMultiPatch<real_t>& cmp, gsMultiBasis<real_t>& mb,
                    const gsFunction<real_t>* wFun, const gsMultiPatch<real_t>& uPrevField,
                    real_t Dt, gsMultiPatch<real_t>& uNextField, real_t& l2err, real_t& h1err,
                    std::vector<real_t>* elErr = nullptr)
{
    const index_t dim = cmp.patch(0).targetDim();
    gsFunctionExpr<> uexFun(exactStr(),dim), fFun(fStr(),dim);
    gsComposedFunction<real_t> cuex(cmp.patch(0), uexFun), cf(cmp.patch(0), fFun);
    gsBoundaryConditions<> bc;
    for (short_t s=1;s<=4;++s) bc.addCondition(s, condition_type::dirichlet, &cuex, 0, true);
    bc.setGeoMap(cmp);

    gsExprAssembler<> A(1,1);
    typedef gsExprAssembler<>::geometryMap geometryMap;
    typedef gsExprAssembler<>::space       space;
    typedef gsExprAssembler<>::solution    solution;
    A.setIntegrationElements(mb);
    A.options().setReal("quA",g_quA); A.options().setInt("quB",2);
    gsOptionList seOff; seOff.addSwitch("SameElement","",false);
    A.options().update(seOff, gsOptionList::addIfUnknown);
    gsExprEvaluator<> ev(A);
    ev.options().setReal("quA",g_quA); ev.options().setInt("quB",2);
    ev.options().update(seOff, gsOptionList::addIfUnknown);

    geometryMap G = A.getMap(cmp);
    space u = A.getSpace(mb);
    auto fsrc  = A.getCoeff(cf);
    auto uprev = A.getCoeff(uPrevField.patch(0));
    auto uex   = ev.getVariable(cuex);
    gsMatrix<real_t> solVector;
    solution usol = A.getSolution(u, solVector);

    u.setup(bc, dirichlet::l2Projection, 0);
    A.initSystem();
    if (wFun) {
        auto w = A.getCoeff(*wFun);
        A.assemble( u*u.tr()*(1.0/Dt)*meas(G)
                  + igrad(u,G)*igrad(u,G).tr()*meas(G)
                  - (igrad(u,G)*w)*u.tr()*meas(G),
                    u*fsrc*meas(G) + u*uprev*(1.0/Dt)*meas(G) );
    } else {
        A.assemble( u*u.tr()*(1.0/Dt)*meas(G)
                  + igrad(u,G)*igrad(u,G).tr()*meas(G),
                    u*fsrc*meas(G) + u*uprev*(1.0/Dt)*meas(G) );
    }
    gsSparseSolver<>::CGDiagonal solver(A.matrix());
    solver.setTolerance(1e-12); solver.setMaxIterations(20000);
    solVector = solver.solve(A.rhs());
    GISMO_ENSURE(solVector.allFinite(), "non-finite solve");
    l2err = math::sqrt( ev.integral( (uex-usol).sqNorm()*meas(G) ) );
    h1err = l2err + math::sqrt( ev.integral( (igrad(uex,G)-igrad(usol,G)).sqNorm()*meas(G) ) );
    if (elErr) { ev.integralElWise( (uex-usol).sqNorm()*meas(G) ); *elErr = ev.elementwise(); }
    usol.extract(uNextField);
}

static void projectExact(const gsMultiPatch<real_t>& cmp, gsMultiBasis<real_t>& mb,
                         gsMultiPatch<real_t>& field, std::vector<real_t>* elErr = nullptr)
{
    const index_t dim = cmp.patch(0).targetDim();
    gsFunctionExpr<> uexFun(exactStr(),dim);
    gsComposedFunction<real_t> cuex(cmp.patch(0), uexFun);
    gsBoundaryConditions<> bc;
    for (short_t s=1;s<=4;++s) bc.addCondition(s, condition_type::dirichlet, &cuex, 0, true);
    bc.setGeoMap(cmp);
    gsExprAssembler<> A(1,1);
    typedef gsExprAssembler<>::geometryMap geometryMap;
    typedef gsExprAssembler<>::space       space;
    typedef gsExprAssembler<>::solution    solution;
    A.setIntegrationElements(mb);
    A.options().setReal("quA",g_quA); A.options().setInt("quB",2);
    gsOptionList seOff; seOff.addSwitch("SameElement","",false);
    A.options().update(seOff, gsOptionList::addIfUnknown);
    geometryMap G = A.getMap(cmp);
    space u = A.getSpace(mb);
    auto uc = A.getCoeff(cuex);
    gsMatrix<real_t> solVector;
    solution usol = A.getSolution(u, solVector);
    u.setup(bc, dirichlet::l2Projection, 0);
    A.initSystem();
    A.assemble( u*u.tr()*meas(G), u*uc*meas(G) );
    gsSparseSolver<>::CGDiagonal solver(A.matrix());
    solver.setTolerance(1e-14); solver.setMaxIterations(20000);
    solVector = solver.solve(A.rhs());
    if (elErr)
    {
        gsExprEvaluator<> ev(A);
        ev.options().setReal("quA",g_quA); ev.options().setInt("quB",2);
        ev.options().update(seOff, gsOptionList::addIfUnknown);
        auto uex = ev.getVariable(cuex);
        ev.integralElWise( (uex-usol).sqNorm()*meas(G) );
        *elErr = ev.elementwise();
    }
    usol.extract(field);
}

// THB basis (identity geometry) refined toward the current band by the MONITOR
// quantity u_ex^2.  For the sech^2 ring this is the value, not the gradient:
// ||grad_S u_ex|| vanishes at the ring's crest and peaks on its two flanks, so
// gradient marking refines two rings and skips the band where the solution's
// mass actually is.  This keeps the THB arm marking on the same feature the
// ValueBased relocation monitor tracks, which is what makes the r/THB/rh
// comparison a comparison of STRATEGIES rather than of monitors.
static gsMultiBasis<real_t> buildTHBforFeature(const gsMultiPatch<real_t>& cmp,
                                             const gsTensorBSplineBasis<2>& base,
                                             index_t nPass, real_t refParam, index_t refExt, index_t refCrit)
{
    gsMultiBasis<> mb; mb.addBasis(gsTHBSplineBasis<2,real_t>(base).clone().release());
    const index_t dim = cmp.patch(0).targetDim();
    for (index_t pass=0; pass<nPass; ++pass){
        gsFunctionExpr<> uexFun(exactStr(),dim);
        gsComposedFunction<real_t> cuex(cmp.patch(0), uexFun);
        gsExprAssembler<> A(1,1); A.setIntegrationElements(mb);
        A.options().setReal("quA",g_quA); A.options().setInt("quB",2);
        gsOptionList seOff; seOff.addSwitch("SameElement","",false);
        A.options().update(seOff, gsOptionList::addIfUnknown);
        gsExprEvaluator<> ev(A); ev.options().setReal("quA",g_quA); ev.options().setInt("quB",2);
        ev.options().update(seOff, gsOptionList::addIfUnknown);
        auto Gm = A.getMap(cmp);
        auto uex = ev.getVariable(cuex);
        ev.integralElWise( uex.sqNorm()*meas(Gm) );
        std::vector<real_t> elErr = ev.elementwise();
        std::vector<bool> marked; gsMarkElementsForRef(elErr, refCrit, refParam, marked);
        gsRefineMarkedElements(mb, marked, refExt);
    }
    return mb;
}

// THB basis refined by Doerfler marking on the element-wise L2 error of the
// discrete solution, as in the steady rh study: each pass solves the current
// step on the mesh built so far, marks on ||u_ex-u_h||^2_{L2(K)}, and refines.
// Unlike the u_ex^2 monitor above, this responds to how well the
// current mesh resolves the front, not only to where the front is.
// Cost: nPass extra linear solves per time step.
static gsMultiBasis<real_t> buildTHBbyError(const gsMultiPatch<real_t>& cmp,
                                            const gsTensorBSplineBasis<2>& base,
                                            index_t nPass, real_t refParam, index_t refExt, index_t refCrit,
                                            const gsFunction<real_t>* wFun,
                                            const gsMultiPatch<real_t>* uPrev, real_t Dt)
{
    gsMultiBasis<> mb; mb.addBasis(gsTHBSplineBasis<2,real_t>(base).clone().release());
    for (index_t pass=0; pass<nPass; ++pass){
        std::vector<real_t> elErr;
        gsMultiPatch<> utmp;
        if (uPrev) { real_t e,eh; aleStep(cmp, mb, wFun, *uPrev, Dt, utmp, e, eh, &elErr); }
        else       { projectExact(cmp, mb, utmp, &elErr); }
        std::vector<bool> marked; gsMarkElementsForRef(elErr, refCrit, refParam, marked);
        gsRefineMarkedElements(mb, marked, refExt);
    }
    return mb;
}

// Per-arm ParaView + per-arm plot CSV output.
//
// The directory layout is not free: scripts/render_panels.py::step_files()
// globs exactly these names, and the two halves disagree on their time tag on
// purpose. gsParaviewCollection always FLOAT-tags its own time steps
// (solution_t0.000000_patch0.vts), while the sigma/mesh snapshots are named
// here and are INTEGER-tagged (sigma_t0.vts). The renderer tries "%f" then
// "%d" precisely because of that split; matching it is what lets the existing
// pipeline read this driver's output with no changes.
//
//   <out>/<arm>/solution_pvd/solution_t<float>_patch0.vts   fields, float tag
//   <out>/<arm>/sigma_steps/sigma_t<int>.vts                integer tag
//   <out>/<arm>/mesh_steps/mesh_t<int>.vtp                  integer tag
//   <out>/<arm>/{geometry,sigma}.vts, <out>/<arm>/mesh.vtp  final state
//   <out>/<arm>/{solution,sigma_steps,mesh_steps}.pvd       time sliders
//
// The "error" field is the SQUARED pointwise error, matching
// poisson_rh_schedule_example; render_panels.py takes its own sqrt.
struct ArmOut
{
    bool                                  on;
    std::string                           dir;
    gsExprEvaluator<>                     pev;   // persistent: the collection holds &pev
    std::unique_ptr<gsParaviewCollection> sol;
    std::vector<index_t>                  steps;
    std::ofstream                         csv;

    ArmOut() : on(false) {}

    /// Opens <base>/<arm>/ and, when \a doPlot, the ParaView collection in it.
    /// The per-arm plot CSV is written either way -- it is the pgfplots input
    /// and costs nothing.
    void open(const std::string& base, const std::string& arm, bool doPlot, index_t plotPoints)
    {
        const std::string sep(1, gsFileManager::getNativePathSeparator());
        dir = base + arm + sep;
        gsFileManager::mkdir(dir);
        csv.open((base+"timeseries_"+arm+".csv").c_str());
        csv << std::unitbuf << "step,t,dofs,l2,h1\n"
            << std::scientific << std::setprecision(8);
        if (!doPlot) return;
        on = true;
        gsFileManager::mkdir(dir+"sigma_steps");
        gsFileManager::mkdir(dir+"mesh_steps");
        sol.reset(new gsParaviewCollection(dir+"solution", &pev));
        sol->options().setSwitch("plotElements", true);
        sol->options().setInt("plotElements.resolution", 4);
        sol->options().setInt("numPoints", plotPoints);
        sol->options().setInt("precision", 12);
    }

    void row(index_t k, real_t t, index_t dofs, real_t l2, real_t h1)
    { csv << k << "," << t << "," << dofs << "," << l2 << "," << h1 << "\n"; }

    /// One time step: the solution collection entry plus the sigma/mesh
    /// snapshots. \a cmp must outlive the call (newTimeStep takes its address).
    void step(gsMultiPatch<real_t>& cmp, const gsMultiBasis<real_t>& mb,
              const gsMultiPatch<real_t>& field, const gsGeometry<real_t>& sigma, index_t k)
    {
        if (!on) return;
        const index_t dim = cmp.patch(0).targetDim();
        gsFunctionExpr<> uexFun(exactStr(), dim);
        // The exact solution is registered THROUGH the geometry map rather than
        // by wrapping it in a gsComposedFunction: both evaluate u_ex at the
        // physical point G(xi), but this is the form poisson_rh_schedule_example
        // uses, so the two drivers plot their fields the same way.
        pev.setIntegrationElements(mb);
        auto pG  = pev.getMap(cmp);
        auto pus = pev.getVariable(field.patch(0));
        auto pue = pev.getVariable(uexFun, pG);
        sol->newTimeStep(&cmp, (real_t)k);
        sol->addField(pus, "numerical solution");
        sol->addField(pue, "exact solution");
        sol->addField((pue-pus).sqNorm(), "error");
        sol->saveTimeStep();
        // gsExprHelper caches evaluated data in maps KEYED BY THE ADDRESS of
        // the source object (m_fdata/m_mdata/m_cdata), and nothing on this path
        // clears them. The caller's cmp is step-local, so the next iteration
        // can place a different geometry at the same address and score a cache
        // HIT against the previous step's data. Dropping the entries here,
        // while their keys are still alive, is what gsExprHelper provides for
        // exactly this case.
        pev.exprData()->cleanUp();
        gsWriteParaview(sigma, dir+"sigma_steps/sigma_t"+std::to_string(k), 1000, true, true);
        gsMesh<real_t> stepMsh(mb.basis(0));
        gsWriteParaview(stepMsh, dir+"mesh_steps/mesh_t"+std::to_string(k), false);
        steps.push_back(k);
    }

    /// Final state + the two hand-rolled .pvd time sliders, so the sigma and
    /// mesh collections share solution.pvd's timeline in the ParaView GUI.
    void close(const gsMultiPatch<real_t>& cmp, const gsMultiBasis<real_t>& mb,
               const gsGeometry<real_t>& sigma)
    {
        csv.close();
        if (!on) return;
        sol->save();
        gsWriteParaview(cmp.patch(0), dir+"geometry", 1000, true, true);
        gsWriteParaview(sigma, dir+"sigma", 1000, true, true);
        gsMesh<real_t> msh(mb.basis(0));
        gsWriteParaview(msh, dir+"mesh", false);
        writeStepsPvd("sigma_steps","sigma",".vts");
        writeStepsPvd("mesh_steps","mesh",".vtp");
    }

private:
    void writeStepsPvd(const std::string& sub, const std::string& stem, const std::string& ext)
    {
        std::ofstream f((dir+sub+".pvd").c_str());
        f << "<?xml version=\"1.0\"?>\n<VTKFile type=\"Collection\" version=\"0.1\">\n<Collection>\n";
        for (size_t i=0;i<steps.size();++i)
            f << "<DataSet timestep=\"" << steps[i] << "\" part=\"0\" file=\""
              << sub << "/" << stem << "_t" << steps[i] << ext << "\"/>\n";
        f << "</Collection>\n</VTKFile>\n";
    }
};

int main(int argc, char** argv)
{
    std::string input = "parametrization/monitor_example_sphere_patch_with_gradient_function.xml";
    // thbBase=12, not 4. THB/rh re-adapt from this base every step and each pass
    // only subdivides what an earlier pass already marked, so whatever the FIRST
    // pass marks is never recovered from. A 4x4 base cannot represent a
    // t_w=0.05 ring at all: the first pass commits to four disconnected blobs
    // and every later pass just refines inside them, leaving the ring's axis
    // crossings coarse. At 12x12 the same marking tracks the ring as a closed
    // annular band, and the late-time error stops growing (final-step L2
    // 2.3e-2 against 8.8e-2). Measured, not guessed -- see
    // Results_transient_ring_*/README.md.
    index_t p=2, compDeg=2, compN=16, Na=24, K=20, relocIt=40, thbPass=4, Kreloc=1, thbMark=0, thbBase=12;
    bool skipReloc=false, sigmaReset=false, useOptimLBFGS=false, plot=false;
    index_t plotPoints=1000;
    // theta=100. The ValueBased monitor is 1+theta*u_ex with u_ex = sech^2(.)
    // bounded by 1, so theta sets the density contrast DIRECTLY: theta=1 asks
    // for a mere 2:1 clustering and barely deforms sigma. Measured on the r arm
    // (N=24, K=8), monotone and saturating:
    //
    //   theta      1      3     10     30    100    300
    //   minDetJs 0.73   0.55   0.41   0.33   0.27   0.25
    //   gain     1.56x  1.86x  2.46x  3.80x  6.66x  7.27x
    //
    // Nothing folds at any of these. 100 is taken as the default because 300
    // buys only 9% more for a 3x larger theta, and its minDetJsigma ~ 0.27
    // matches the schedule study's R steps (0.26..0.32). theta=1 -- the value
    // this driver shipped with -- understates the method by a factor of 4.
    real_t smoothing=100.0, penalty=1e-4, T=1.0, c0=0.35, c1=0.70;
    std::string tLayer="0.05";
    std::string output="transient_sphere_output";
    gsCmdLine cmd("Transient moving-front heat equation on the exact sphere patch.");
    cmd.addString("i","input","Sphere-patch xml",input);
    cmd.addString("t","layer","Front width tw",tLayer);
    cmd.addInt("K","steps","Time steps",K);
    cmd.addInt("N","Na","Fixed analysis mesh per direction",Na);
    cmd.addInt("","compN","Deformation sigma mesh per direction",compN);
    cmd.addInt("","relocIt","Warm-start relocation iters per step",relocIt);
    cmd.addInt("","Kreloc","Relocate sigma every Kreloc steps (static in between)",Kreloc);
    cmd.addReal("","c0","Front start colatitude",c0);
    cmd.addReal("","c1","Front end colatitude",c1);
    cmd.addInt("","thbPass","THB feature-refinement passes per step",thbPass);
    cmd.addInt("","thbMark","THB/rh marking quantity: 0=u_ex^2 monitor, 1=element-wise discrete L2 error",thbMark);
    cmd.addInt("","thbBase","Elements per direction of the THB/rh coarse base mesh",thbBase);
    cmd.addSwitch("","plot","Write the ParaView output set (per-arm, in the layout scripts/render_panels.py reads)",plot);
    cmd.addInt("","plotPoints","Samples per patch for the plotted fields under --plot",plotPoints);
    cmd.addSwitch("","optimLBFGS","Use gsOptim L-BFGS for the R step instead of HLBFGS (known to stall silently)",useOptimLBFGS);
    cmd.addSwitch("","skipReloc","Run only the uniform and THB arms (skip the relocated r and rh arms)",skipReloc);
    cmd.addSwitch("","sigmaReset","Relocate sigma from the IDENTITY every step instead of warm-starting it from the previous step's sigma",sigmaReset);
    cmd.addReal("S","smoothing","Monitor smoothing theta (ValueBased: O(1), not the front's 1e-2)",smoothing);
    cmd.addReal("P","penalty","Fold-barrier penalty",penalty);
    cmd.addReal("T","final","Final time",T);
    cmd.addString("o","output","output prefix/directory",output);
    try { cmd.getValues(argc,argv); } catch (int rv) { return rv; }
    g_t=tLayer; g_hlbfgs = !useOptimLBFGS;
    const real_t Dt=T/K, cdot=(c1-c0)/T;
    { std::ostringstream o; o<<cdot; g_cdot=o.str(); }
    GISMO_ENSURE(gsFileManager::fileExists(input), "Input not found: "<<input);

    if (output.empty() || output.back()!=gsFileManager::getNativePathSeparator())
        output += gsFileManager::getNativePathSeparator();
    gsFileManager::mkdir(output);

    gsOptionList opt;
    opt.addString("i","Sphere-patch xml",input);
    opt.addString("t","Front width tw",tLayer);
    opt.addInt("K","Time steps",K);
    opt.addInt("N","Fixed analysis mesh per direction",Na);
    opt.addInt("compN","Deformation sigma mesh per direction",compN);
    opt.addInt("relocIt","Warm-start relocation iters per step",relocIt);
    opt.addInt("Kreloc","Relocate sigma every Kreloc steps",Kreloc);
    opt.addReal("c0","Front start colatitude",c0);
    opt.addReal("c1","Front end colatitude",c1);
    opt.addInt("thbPass","THB feature-refinement passes per step",thbPass);
    opt.addInt("thbMark","THB/rh marking quantity",thbMark);
    opt.addInt("thbBase","Elements per direction of the THB/rh coarse base mesh",thbBase);
    opt.addSwitch("plot","Write the ParaView output set",plot);
    opt.addInt("plotPoints","Samples per patch for the plotted fields",plotPoints);
    opt.addSwitch("optimLBFGS","gsOptim L-BFGS R step instead of HLBFGS",useOptimLBFGS);
    opt.addSwitch("skipReloc","Run only the uniform and THB arms",skipReloc);
    opt.addSwitch("sigmaReset","Relocate sigma from the identity every step",sigmaReset);
    opt.addReal("smoothing","Monitor smoothing theta",smoothing);
    opt.addReal("penalty","Fold-barrier penalty",penalty);
    opt.addReal("T","Final time",T);
    gsFileData<> fdout; fdout.add(opt); fdout.save(output+"options.xml");

    // Per-step machine-readable log. Columns mirror the frozen convergence.csv
    // schema shared with examples/poisson_rh_schedule_example.cpp and consumed
    // by Results_schedule_study/schedule_harvest.py and examples/rh_harvest.py;
    // "path" uses U/R/T/H here (uniform/r-ALE/THB/rh) rather than the poisson
    // driver's C/P (composed/projected), since this driver has no R/H/U-letter
    // schedule steps -- every row is a solve ("S"). minErr/maxErr are left
    // empty: this driver has no per-element error vector to report a range over.
    std::ofstream csv(output+"convergence.csv");
    csv << std::unitbuf;
    csv << "cycle,step,path,dofs,dofs_sigma,minErr,maxErr,err,pctBelowTol,minDetJsigma,time\n";
    csv << std::scientific << std::setprecision(8);

    gsFileData<> fd(input); gsMultiPatch<> geomMP;
    if (fd.hasLabel("geometry")) fd.getLabel("geometry",geomMP);
    else                         geomMP.addPatch(*fd.getFirst<gsGeometry<>>());
    gsGeometry<>::uPtr S = geomMP.patch(0).clone();

    gsInfo<<"Transient heat on sphere patch: band width tw="<<g_t<<", colatitude "<<c0<<"->"<<c1
          <<", "<<K<<" steps, Dt="<<Dt<<", analysis "<<Na<<"x"<<Na<<", sigma "<<compN<<"x"<<compN<<"\n";

    gsKnotVector<> kvA(0,1,Na-1,p+1);
    gsTensorBSplineBasis<2> tpA(kvA,kvA);
    gsGeometry<>::uPtr sigId = makeIdentity(compDeg, compN);

    std::vector<real_t> errU(K,0), errR(K,0), errT(K,0), errRH(K,0);
    std::vector<real_t> errU1(K,0), errR1(K,0), errT1(K,0), errRH1(K,0);
    std::vector<index_t> dofT(K,0), dofRH(K,0);
    real_t wallU=0, wallR=0, wallT=0, wallRH=0;
    ArmOut outU, outR, outT, outH;
    outU.open(output,"U",plot,plotPoints); outT.open(output,"T",plot,plotPoints);
    if (!skipReloc) { outR.open(output,"R",plot,plotPoints); outH.open(output,"H",plot,plotPoints); }
    const index_t dofFixed=(Na+p)*(Na+p);

    // ---------- static uniform (identity sigma, w=0) ----------
    {
        gsStopwatch clk;
        gsMultiPatch<> cmp; cmp.addPatch(gsComposedGeometry<real_t>(*sigId,*S));
        gsMultiBasis<> mb; mb.addBasis(tpA.clone().release());
        g_c=std::to_string(c0);
        gsMultiPatch<> un; projectExact(cmp, mb, un);
        for (index_t k=1;k<=K;++k){
            gsStopwatch stepClk;
            const real_t ck=c0+(c1-c0)*real_t(k)/real_t(K); g_c=std::to_string(ck);
            gsMultiPatch<> unext; real_t e,eh; aleStep(cmp, mb, nullptr, un, Dt, unext, e, eh);
            errU[k-1]=e; errU1[k-1]=eh; un=unext;
            const real_t tStep=stepClk.stop();
            csv<<k<<",S,U,"<<dofFixed<<","<<sigId->coefs().size()<<",,,"<<e<<",0,1.0,"<<tStep<<"\n";
            outU.row(k, k*Dt, dofFixed, e, eh);
            outU.step(cmp, mb, un, *sigId, k);
        }
        outU.close(cmp, mb, *sigId);
        wallU=clk.stop();
    }
    // ---------- r-adaptivity (ALE, fixed mesh, relocated sigma) ----------
    if (!skipReloc)
    {
        gsStopwatch clk;
        gsMultiBasis<> mb; mb.addBasis(tpA.clone().release());
        g_c=std::to_string(c0);
        real_t disp0=0;
        gsGeometry<>::uPtr sigPrev = relocateFrom(*sigId, *S, smoothing, penalty, 250, &disp0);
        warnIfStalled(disp0, 0);
        gsMultiPatch<> cmp0; cmp0.addPatch(gsComposedGeometry<real_t>(*sigPrev,*S));
        gsMultiPatch<> un; projectExact(cmp0, mb, un);
        for (index_t k=1;k<=K;++k){
            gsStopwatch stepClk;
            const real_t ck=c0+(c1-c0)*real_t(k)/real_t(K); g_c=std::to_string(ck);
            gsMultiPatch<> unext; real_t e,eh;
            gsMultiPatch<> cmp;
            // sigCur is declared at LOOP scope, not inside the branch: cmp's
            // gsComposedGeometry stores a REFERENCE to it, and everything after
            // this if/else -- the plot and close calls -- dereferences that
            // geometry. A sigma scoped to the branch dies first and the
            // composed basis is then read through a dangling pointer.
            gsGeometry<>::uPtr sigCur;
            if ((k-1)%Kreloc==0){
                real_t disp=0;
                sigCur = relocateFrom(sigmaReset? *sigId : *sigPrev, *S, smoothing, penalty, relocIt, &disp);
                warnIfStalled(disp, k);
                gsComposedGeometry<real_t> Gnew(*sigCur,*S), Gprev(*sigPrev,*S);
                MeshVel w(Gnew,Gprev,Dt);
                cmp.addPatch(gsComposedGeometry<real_t>(*sigCur,*S));
                aleStep(cmp, mb, &w, un, Dt, unext, e, eh);
                sigPrev = sigCur->clone();
            } else {
                sigCur = sigPrev->clone();
                cmp.addPatch(gsComposedGeometry<real_t>(*sigCur,*S));
                aleStep(cmp, mb, nullptr, un, Dt, unext, e, eh);
            }
            errR[k-1]=e; errR1[k-1]=eh; un=unext;
            const real_t tStep=stepClk.stop();
            csv<<k<<",S,R,"<<dofFixed<<","<<sigPrev->coefs().size()<<",,,"<<e<<",0,"
               <<sampleMinDetJ(*sigPrev)<<","<<tStep<<"\n";
            outR.row(k, k*Dt, dofFixed, e, eh);
            outR.step(cmp, mb, un, *sigCur, k);
            if (k==K) outR.close(cmp, mb, *sigCur);
        }
        wallR=clk.stop();
    }
    // ---------- THB (feature-tracking, re-adapt each step, identity geometry) ----------
    {
        gsStopwatch clk;
        gsKnotVector<> kvB(0,1,thbBase-1,p+1); gsTensorBSplineBasis<2> base(kvB,kvB);
        gsMultiPatch<> cmp; cmp.addPatch(gsComposedGeometry<real_t>(*sigId,*S));
        g_c=std::to_string(c0);
        gsMultiBasis<> mb0 = thbMark ? buildTHBbyError(cmp, base, thbPass, 0.85, 1, 3, nullptr, nullptr, Dt)
                                     : buildTHBforFeature(cmp, base, thbPass, 0.85, 1, 3);
        gsMultiPatch<> un; projectExact(cmp, mb0, un);
        for (index_t k=1;k<=K;++k){
            gsStopwatch stepClk;
            const real_t ck=c0+(c1-c0)*real_t(k)/real_t(K); g_c=std::to_string(ck);
            gsMultiBasis<> mb = thbMark ? buildTHBbyError(cmp, base, thbPass, 0.85, 1, 3, nullptr, &un, Dt)
                                        : buildTHBforFeature(cmp, base, thbPass, 0.85, 1, 3);
            gsMultiPatch<> unext; real_t e,eh; aleStep(cmp, mb, nullptr, un, Dt, unext, e, eh);
            errT[k-1]=e; errT1[k-1]=eh; dofT[k-1]=mb.basis(0).size(); un=unext;
            const real_t tStep=stepClk.stop();
            csv<<k<<",S,T,"<<dofT[k-1]<<","<<sigId->coefs().size()<<",,,"<<e<<",0,1.0,"<<tStep<<"\n";
            outT.row(k, k*Dt, dofT[k-1], e, eh);
            outT.step(cmp, mb, un, *sigId, k);
            if (k==K) outT.close(cmp, mb, *sigId);
        }
        wallT=clk.stop();
    }
    // ---------- rh (relocated sigma + per-step THB, ALE) ----------
    if (!skipReloc)
    {
        gsStopwatch clk;
        gsKnotVector<> kvB(0,1,thbBase-1,p+1); gsTensorBSplineBasis<2> base(kvB,kvB);
        g_c=std::to_string(c0);
        real_t disp0=0;
        gsGeometry<>::uPtr sigPrev = relocateFrom(*sigId, *S, smoothing, penalty, 250, &disp0);
        warnIfStalled(disp0, 0);
        gsMultiPatch<> cmp0; cmp0.addPatch(gsComposedGeometry<real_t>(*sigPrev,*S));
        gsMultiBasis<> mb0 = thbMark ? buildTHBbyError(cmp0, base, thbPass, 0.85, 1, 3, nullptr, nullptr, Dt)
                                     : buildTHBforFeature(cmp0, base, thbPass, 0.85, 1, 3);
        gsMultiPatch<> un; projectExact(cmp0, mb0, un);
        for (index_t k=1;k<=K;++k){
            gsStopwatch stepClk;
            const real_t ck=c0+(c1-c0)*real_t(k)/real_t(K); g_c=std::to_string(ck);
            gsGeometry<>::uPtr sigCur; bool moved=false;
            if ((k-1)%Kreloc==0){
                real_t disp=0;
                gsGeometry<>::uPtr sigNew = relocateFrom(sigmaReset? *sigId : *sigPrev, *S, smoothing, penalty, relocIt, &disp);
                warnIfStalled(disp, k);
                sigCur = sigNew->clone(); moved=true;
            } else sigCur = sigPrev->clone();
            gsComposedGeometry<real_t> Gcur(*sigCur,*S), Gprev(*sigPrev,*S);
            MeshVel w(Gcur,Gprev,Dt);
            gsMultiPatch<> cmp; cmp.addPatch(gsComposedGeometry<real_t>(*sigCur,*S));
            gsMultiBasis<> mb = thbMark ? buildTHBbyError(cmp, base, thbPass, 0.85, 1, 3, moved? &w : nullptr, &un, Dt)
                                        : buildTHBforFeature(cmp, base, thbPass, 0.85, 1, 3);
            gsMultiPatch<> unext; real_t e,eh;
            aleStep(cmp, mb, moved? &w : nullptr, un, Dt, unext, e, eh);
            const real_t detJcur = sampleMinDetJ(*sigCur);
            if (moved) sigPrev = sigCur->clone();
            errRH[k-1]=e; errRH1[k-1]=eh; dofRH[k-1]=mb.basis(0).size(); un=unext;
            const real_t tStep=stepClk.stop();
            csv<<k<<",S,H,"<<dofRH[k-1]<<","<<sigCur->coefs().size()<<",,,"<<e<<",0,"
               <<detJcur<<","<<tStep<<"\n";
            outH.row(k, k*Dt, dofRH[k-1], e, eh);
            outH.step(cmp, mb, un, *sigCur, k);
            if (k==K) outH.close(cmp, mb, *sigCur);
        }
        wallRH=clk.stop();
    }

    gsInfo<<"\n"<<std::left<<std::setw(6)<<"step"<<std::setw(8)<<"t"
          <<std::setw(14)<<"uniform L2"<<std::setw(14)<<"r(ALE) L2"<<std::setw(14)<<"THB L2"
          <<std::setw(14)<<"rh L2"<<std::setw(9)<<"THB DoF"<<"\n"<<std::string(74,'-')<<"\n";
    real_t mu=0,mr=0,mt=0,mrh=0,mu1=0,mr1=0,mt1=0,mrh1=0; real_t adofT=0,adofRH=0;
    for (index_t k=0;k<K;++k){
        gsInfo<<std::left<<std::setw(6)<<(k+1)<<std::fixed<<std::setprecision(3)<<std::setw(8)<<((k+1)*Dt)
              <<std::scientific<<std::setprecision(3)<<std::setw(14)<<errU[k]<<std::setw(14)<<errR[k]
              <<std::setw(14)<<errT[k]<<std::setw(14)<<errRH[k]<<std::fixed<<std::setw(9)<<dofT[k]<<"\n";
        mu=math::max(mu,errU[k]); mr=math::max(mr,errR[k]); mt=math::max(mt,errT[k]); mrh=math::max(mrh,errRH[k]);
        mu1=math::max(mu1,errU1[k]); mr1=math::max(mr1,errR1[k]); mt1=math::max(mt1,errT1[k]); mrh1=math::max(mrh1,errRH1[k]);
        adofT+=dofT[k]; adofRH+=dofRH[k];
    }
    adofT/=K; adofRH/=K;
    gsInfo<<std::string(74,'-')<<"\n";
    gsInfo<<"DoF:  uniform/r (fixed) = "<<dofFixed<<",  THB (avg) = "<<std::fixed<<std::setprecision(0)<<adofT
          <<",  rh (avg) = "<<adofRH<<"\n";
    gsInfo<<"max H1 over time:  uniform = "<<std::scientific<<std::setprecision(3)<<mu1
          <<",  r(ALE) = "<<mr1<<",  THB = "<<mt1<<",  rh = "<<mrh1<<"\n";
    gsInfo<<"max L2 over time:  uniform = "<<std::scientific<<std::setprecision(3)<<mu
          <<",  r(ALE) = "<<mr<<",  THB = "<<mt<<",  rh = "<<mrh<<"\n";
    gsInfo<<std::fixed<<std::setprecision(3)
          <<"wall-clock:  uniform = "<<wallU<<" s,  r(ALE) = "<<wallR<<" s,  THB = "<<wallT<<" s,  rh = "<<wallRH<<" s\n";
    return 0;
}
