#!/bin/bash
# hooks/_compiler_settings

# Compiler setting
shopt -s extglob;
case "$IMAGE_NAME" in

    # Clang
    
    ?(*\-)clang6.0?(\-*))
        CC=clang-6.0
        CXX=clang++-6.0
        ;;
    ?(*\-)clang7?(\-*))
        CC=clang-7
        CXX=clang++-7
        ;;
    ?(*\-)clang8?(\-*))
        CC=clang-8
        CXX=clang++-8
        ;;
    ?(*\-)clang9?(\-*))
        CC=clang-9
        CXX=clang++-9
        ;;
    ?(*\-)clang10?(\-*))
        CC=clang-10
        CXX=clang++-10
        ;;
    ?(*\-)clang11?(\-*))
        CC=clang-11
        CXX=clang++-11
        ;;

    # GCC

    ?(*\-)gcc7?(\-*))
        CC=gcc-7
        CXX=g++-7
        FC=gfortran-7
        ;;
    ?(*\-)gcc8?(\-*))
        CC=gcc-8
        CXX=g++-8
        FC=gfortran-8
        ;;
    ?(*\-)gcc9?(\-*))
        CC=gcc-9
        CXX=g++-9
        FC=gfortran-9
        ;;
    ?(*\-)gcc10?(\-*))
        CC=gcc-10
        CXX=g++-10
        FC=gfortran-10
        ;;
    ?(*\-)gcc11?(\-*))
        CC=gcc-11
        CXX=g++-11
        FC=gfortran-11
        ;;
                      
    *)
        echo "[***] Unsupported compiler"
        exit 1
        ;;
esac
shopt -u extglob;

echo "[---] CC:                     ${CC}"
echo "[---] CXX:                    ${CXX}"
echo "[---] FC:                     ${FC}"
