/** @file gsDofMapper_test.cpp

    @brief Regression tests for the gismo::gsDofMapper
    (gsCore/gsDofMapper.h) against commit 2fa5bee4466c18a1bf9baa099dd2b87f8224832f

    Every expected value in this file is a literal that was generated by
    running the fixtures below on revision 2fa5bee44 and pasting the printed
    result back in.  Nothing here recomputes an expectation through a second
    code path, so a later rewrite of the internal storage of gsDofMapper
    cannot silently move an expectation along with the implementation.

    This file is part of the G+Smo library.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
**/

#include "gismo_unittest.h"
#include <gsAssembler/gsDofMapperCreator.h>

#include <limits>

using namespace gismo;

namespace {

// Pins one observable string.  The tag is prefixed to both sides so that a
// failing assertion names the pinned area without any extra plumbing.
#define PIN(tag, expected, actual) \
    CHECK_EQUAL(std::string(tag "|") + (expected), std::string(tag "|") + (actual))

index_t nPatches(const gsDofMapper & m)
{ return static_cast<index_t>(m.numPatches()); }

std::string join(const gsVector<index_t> & v)
{
    std::ostringstream os;
    os << "[";
    for (index_t i = 0; i != v.size(); ++i)
        os << (i ? "," : "") << v[i];
    os << "]";
    return os.str();
}

std::string join(const std::vector<index_t> & v)
{
    std::ostringstream os;
    os << "[";
    for (size_t i = 0; i != v.size(); ++i)
        os << (i ? "," : "") << v[i];
    os << "]";
    return os.str();
}

std::string join(const std::vector<std::pair<index_t,index_t> > & v)
{
    std::ostringstream os;
    os << "[";
    for (size_t i = 0; i != v.size(); ++i)
        os << (i ? "," : "") << "(" << v[i].first << "," << v[i].second << ")";
    os << "]";
    return os.str();
}

// --- scalar/aggregate counters -------------------------------------------

// componentsSize, numComponents, numPatches, mapSize, size, freeSize,
// boundarySize, boundarySizeWithDuplicates, coupledSize, taggedSize,
// allFree, isPermutation, isFinalized.
std::string dumpCounts(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "comps="   << m.componentsSize()
       << " ncomp="  << m.numComponents()
       << " npatch=" << m.numPatches()
       << " map="    << m.mapSize()
       << " size="   << m.size()
       << " free="   << m.freeSize()
       << " elim="   << m.boundarySize()
       << " cpld="   << m.coupledSize()
       << " tagged=" << m.taggedSize()
       << " allfree="<< (m.allFree() ? 1 : 0)
       << " perm="   << (m.isPermutation() ? 1 : 0)
       << " final="  << (m.isFinalized() ? 1 : 0);
    return os.str();
}

// boundarySizeWithDuplicates().  Kept out of dumpCounts because its
// multi-component answers used to be defective: it counted, per component,
// the entries above that component's own freeSize(i) instead of the global
// free count, so it reported the later components' free dofs as eliminated.
std::string dumpElimDup(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "elimdup=" << m.boundarySizeWithDuplicates();
    return os.str();
}

// Per-component size(c), freeSize(c), totalSize(c).
std::string dumpPerComponent(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t c = 0; c != m.numComponents(); ++c)
        os << (c ? " " : "") << "c" << c
           << ":size=" << m.size(c)
           << ",free=" << m.freeSize(c)
           << ",total=" << m.totalSize(c);
    return os.str();
}

// offset(k) for every patch and patchSize(k,c) for every (patch,component).
std::string dumpLayout(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "off=[";
    for (index_t k = 0; k != nPatches(m); ++k)
        os << (k ? "," : "") << m.offset(k);
    os << "] ps=";
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? " " : "") << "c" << c << ":[";
        for (index_t k = 0; k != nPatches(m); ++k)
            os << (k ? "," : "") << m.patchSize(k, c);
        os << "]";
    }
    return os.str();
}

// firstIndex(0) and lastIndex().  See first_index_is_the_smallest_index_of_
// the_component for firstIndex(c) with c>=1.
std::string dumpFirstLast(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "first0=" << m.firstIndex(0) << " last=" << m.lastIndex();
    return os.str();
}

// --- index maps -----------------------------------------------------------

std::string dumpAsVector(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t c = 0; c != m.numComponents(); ++c)
        os << (c ? " " : "") << "c" << c << join(m.asVector(c));
    return os.str();
}

// mapIndex(n) over the full flat range [0, mapSize()).
std::string dumpMapIndex(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "[";
    for (size_t n = 0; n != m.mapSize(); ++n)
        os << (n ? "," : "") << m.mapIndex(static_cast<index_t>(n));
    os << "]";
    return os.str();
}

// index(i,k,c) for every local dof of every patch and component.
std::string dumpIndex(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? ";" : "") << "c" << c;
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            os << "|";
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
                os << (i ? "," : "") << m.index(i, k, c);
        }
    }
    return os.str();
}

// freeIndex(i,k,c) for every local dof.  Unlike index(), freeIndex does not
// add m_shift; on a shifted mapper this is the discriminator between the two.
std::string dumpFreeIndex(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? ";" : "") << "c" << c;
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            os << "|";
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
                os << (i ? "," : "") << m.freeIndex(i, k, c);
        }
    }
    return os.str();
}

// localToGlobal(locals,k,globals,c) on the full local range of every patch.
std::string dumpLocalToGlobal(const gsDofMapper & m, const index_t c)
{
    std::ostringstream os;
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        const index_t n = static_cast<index_t>(m.patchSize(k, c));
        gsMatrix<index_t> locals(n, 1), globals;
        for (index_t i = 0; i != n; ++i)
            locals(i, 0) = i;
        m.localToGlobal(locals, k, globals, c);
        os << (k ? " " : "") << "k" << k << ":"
           << globals.rows() << "x" << globals.cols() << "[";
        for (index_t i = 0; i != globals.rows(); ++i)
            os << (i ? "," : "") << globals(i, 0);
        os << "]";
    }
    return os.str();
}

// localToGlobal2(locals,k,globals,numFree,c) on the full local range of every
// patch: the returned numFree plus the full two-column result.  Column 0 is
// the position in locals and column 1 the global index; the free entries are
// packed from the top and the eliminated ones from the bottom.
std::string dumpLocalToGlobal2(const gsDofMapper & m, const index_t c)
{
    std::ostringstream os;
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        const index_t n = static_cast<index_t>(m.patchSize(k, c));
        gsMatrix<index_t> locals(n, 1), globals;
        for (index_t i = 0; i != n; ++i)
            locals(i, 0) = i;
        index_t numFree = -1;
        m.localToGlobal2(locals, k, globals, numFree, c);
        os << (k ? " " : "") << "k" << k << ":nfree=" << numFree << " "
           << globals.rows() << "x" << globals.cols() << "[";
        for (index_t i = 0; i != globals.rows(); ++i)
            os << (i ? "," : "") << "(" << globals(i, 0) << "," << globals(i, 1) << ")";
        os << "]";
    }
    return os.str();
}

// is_free(i,k,c) / is_boundary(i,k,c) as one character per local dof.
// 'F' free, 'B' eliminated, '?' if the two predicates disagree.
std::string dumpFreeBoundaryFlags(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? ";" : "");
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            if (k) os << "|";
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
            {
                const bool f = m.is_free    (i, k, c);
                const bool b = m.is_boundary(i, k, c);
                os << (f == b ? '?' : (f ? 'F' : 'B'));
            }
        }
    }
    return os.str();
}

// bindex(i,k,c) for the local dofs that are eliminated.
std::string dumpBindex(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "[";
    bool first = true;
    for (index_t c = 0; c != m.numComponents(); ++c)
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
                if (m.is_boundary(i, k, c))
                {
                    os << (first ? "" : ",") << c << ":" << k << ":" << i
                       << "->" << m.bindex(i, k, c);
                    first = false;
                }
        }
    os << "]";
    return os.str();
}

// is_free_index / is_boundary_index over the shifted global range, plus
// global_to_bindex on the eliminated ones.
std::string dumpGlobalFlags(const gsDofMapper & m, const index_t shift)
{
    std::ostringstream os;
    for (index_t gl = shift; gl != shift + m.size(); ++gl)
    {
        const bool f = m.is_free_index    (gl);
        const bool b = m.is_boundary_index(gl);
        os << (f == b ? '?' : (f ? 'F' : 'B'));
    }
    os << " gbi=[";
    bool first = true;
    for (index_t gl = shift; gl != shift + m.size(); ++gl)
        if (m.is_boundary_index(gl))
        {
            os << (first ? "" : ",") << gl << "->" << m.global_to_bindex(gl);
            first = false;
        }
    os << "]";
    return os.str();
}

// findBoundary(k,c) and findFree(k,c) for every patch.
std::string dumpFindBoundaryFree(const gsDofMapper & m, const index_t c = 0)
{
    std::ostringstream os;
    os << "bnd=";
    for (index_t k = 0; k != nPatches(m); ++k)
        os << (k ? "," : "") << join(m.findBoundary(k, c));
    os << " free=";
    for (index_t k = 0; k != nPatches(m); ++k)
        os << (k ? "," : "") << join(m.findFree(k, c));
    return os.str();
}

// indexOnPatch(gl,k,local) over every stored global index and every patch.
// The loop deliberately runs over the UNSHIFTED range [0,size()) because
// indexOnPatch compares against the stored (unshifted) dof values.
std::string dumpIndexOnPatch(const gsDofMapper & m)
{
    std::ostringstream os;
    for (index_t gl = 0; gl != m.size(); ++gl)
    {
        os << (gl ? " " : "") << gl << ":";
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            index_t local = -12345;
            if (m.indexOnPatch(gl, k, local)) os << local;
            else                              os << "-";
            if (k + 1 != nPatches(m)) os << "/";
        }
    }
    return os.str();
}

// --- coupled queries ------------------------------------------------------

// is_coupled / is_coupled_index / cindex / findCoupled / findFreeUncoupled
// for component \a c.  The gflags column (is_coupled_index over the whole
// global range) is component-independent and therefore repeats verbatim for
// every c; it is kept in so that each component's literal stands on its own.
std::string dumpCoupledQueries(const gsDofMapper & m, const index_t c = 0)
{
    std::ostringstream os;
    os << "flags=";
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        if (k) os << "|";
        const index_t n = static_cast<index_t>(m.patchSize(k, c));
        for (index_t i = 0; i != n; ++i)
            os << (m.is_coupled(i, k, c) ? 'C' : '.');
    }
    os << " cidx=[";
    bool first = true;
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        const index_t n = static_cast<index_t>(m.patchSize(k, c));
        for (index_t i = 0; i != n; ++i)
            if (m.is_coupled(i, k, c))
            {
                os << (first ? "" : ",") << k << ":" << i
                   << "->" << m.cindex(i, k, c);
                first = false;
            }
    }
    os << "] gflags=";
    for (index_t gl = 0; gl != m.size(); ++gl)
        os << (m.is_coupled_index(gl) ? 'C' : '.');
    os << " findCoupled=";
    for (index_t k = 0; k != nPatches(m); ++k)
        os << (k ? "," : "") << join(m.findCoupled(k, -1, c));
    os << " findCoupledPairs=";
    for (index_t k = 0; k != nPatches(m); ++k)
        for (index_t j = 0; j != nPatches(m); ++j)
            os << ((k || j) ? "," : "") << k << j << join(m.findCoupled(k, j, c));
    os << " findFreeUncoupled=";
    for (index_t k = 0; k != nPatches(m); ++k)
        os << (k ? "," : "") << join(m.findFreeUncoupled(k, c));
    return os.str();
}

// inverseOnPatch(k) as a flat string.
std::string dumpInverseOnPatch(const gsDofMapper & m, const index_t k)
{
    const std::map<index_t,index_t> inv = m.inverseOnPatch(k);
    std::ostringstream os;
    os << "[";
    for (std::map<index_t,index_t>::const_iterator it = inv.begin();
         it != inv.end(); ++it)
        os << (it == inv.begin() ? "" : ",") << "(" << it->first << "," << it->second << ")";
    os << "]";
    return os.str();
}

// --- component / pre-image queries (zero shift only) ----------------------

std::string dumpComponentOf(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "[";
    for (index_t gl = 0; gl != m.size(); ++gl)
        os << (gl ? "," : "") << m.componentOf(gl);
    os << "]";
    return os.str();
}

std::string dumpPreImages(const gsDofMapper & m)
{
    std::ostringstream os;
    std::vector<std::pair<index_t,index_t> > pre;
    for (index_t gl = 0; gl != m.size(); ++gl)
    {
        m.preImage(gl, pre);
        os << (gl ? " " : "") << gl << join(pre);
    }
    return os.str();
}

std::string dumpAnyPreImage(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "[";
    for (index_t gl = 0; gl != m.size(); ++gl)
    {
        const std::pair<index_t,index_t> p = m.anyPreImage(gl);
        os << (gl ? "," : "") << "(" << p.first << "," << p.second << ")";
    }
    os << "]";
    return os.str();
}

// --- tagged queries (zero shift only) -------------------------------------

std::string dumpTagged(const gsDofMapper & m)
{
    std::ostringstream os;
    os << "tagged=" << join(m.getTagged())
       << " n=" << m.taggedSize()
       << " gflags=";
    for (index_t gl = 0; gl != m.size(); ++gl)
        os << (m.is_tagged_index(gl) ? 'T' : '.');
    os << " flags=";
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? ";" : "");
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            if (k) os << "|";
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
                os << (m.is_tagged(i, k, c) ? 'T' : '.');
        }
    }
    os << " tindex=";
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        os << (c ? ";" : "");
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            if (k) os << "|";
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
                os << (i ? "," : "") << m.tindex(i, k, c);
        }
    }
    return os.str();
}

// --- fixtures -------------------------------------------------------------

// F1: one patch with six local dofs, one component, nothing coupled and
// nothing eliminated.  The simplest possible finalized mapper.
gsDofMapper singlePatchPlain()
{
    gsVector<index_t> sz(1);
    sz[0] = 6;
    gsDofMapper m(sz, 1);
    m.finalize();
    return m;
}

// F2: two patches of six local dofs each, one component.  Three matchDof
// calls build two coupling groups (the second one holds three local dofs),
// two plain free dofs are eliminated, and two dofs are tagged after
// finalize().
gsDofMapper twoPatchCoupledElim()
{
    gsVector<index_t> sz(2);
    sz[0] = 6; sz[1] = 6;
    gsDofMapper m(sz, 1);
    m.matchDof(0, 4, 1, 0);   // coupling group A: (0,4) ~ (1,0)
    m.matchDof(0, 5, 1, 1);   // coupling group B: (0,5) ~ (1,1)
    m.matchDof(1, 2, 0, 5);   // extends group B by (1,2)
    m.eliminateDof(0, 0);     // plain free dof of patch 0
    m.eliminateDof(3, 1);     // plain free dof of patch 1
    m.finalize();
    m.markTagged(1, 0);
    m.markTagged(4, 1);
    return m;
}

// F3: two patches of four and five local dofs, three components.  Each
// component gets a different matching and elimination pattern, so the three
// components end up with different free/coupled/eliminated counts.  This is
// what exercises the per-component prefix arrays and the multi-component
// re-offset pass at the end of finalize().
gsDofMapper threeCompUniform()
{
    gsVector<index_t> sz(2);
    sz[0] = 4; sz[1] = 5;
    gsDofMapper m(sz, 3);

    // component 0: one coupling pair, one eliminated dof
    m.matchDof(0, 3, 1, 0, 0);
    m.eliminateDof(0, 0, 0);

    // component 1: two coupling pairs, two eliminated dofs
    m.matchDof(0, 2, 1, 1, 1);
    m.matchDof(0, 3, 1, 2, 1);
    m.eliminateDof(4, 1, 1);
    m.eliminateDof(0, 0, 1);

    // component 2: no coupling, one eliminated dof
    m.eliminateDof(3, 1, 2);

    m.finalize();
    return m;
}

// F4: F3 with a nonzero global shift and a nonzero boundary shift.
gsDofMapper threeCompShifted()
{
    gsDofMapper m = threeCompUniform();
    m.setShift(100);
    m.setBoundaryShift(7);
    return m;
}

// F5: the identity/aliased layout: three patches, seven (already global)
// dofs, two components.
gsDofMapper identityMapper()
{
    gsDofMapper m;
    m.setIdentity(3, 7, 2);
    m.finalize();
    return m;
}

// F6: F3, then all coupled dofs are tagged and the free block of component 0
// is permuted by an explicit non-trivial permutation of length freeSize(0).
gsDofMapper permutedMapper()
{
    gsDofMapper m = threeCompUniform();
    m.markCoupledAsTagged();
    gsVector<index_t> perm(7);      // freeSize(0) == 7 on F3
    perm << 3, 0, 6, 1, 5, 2, 4;
    m.permuteFreeDofs(perm, 0);
    return m;
}

// F7: two patches of five local dofs, one component, and a single
// collapseDofs call gluing the local dofs 0, 2 and 4 of patch 0 together.
gsDofMapper collapsedMapper()
{
    gsVector<index_t> sz(2);
    sz[0] = 5; sz[1] = 5;
    gsDofMapper m(sz, 1);
    gsMatrix<unsigned> b(3, 1);
    b(0, 0) = 0; b(1, 0) = 2; b(2, 0) = 4;
    m.colapseDofs(0, b);
    m.finalize();
    return m;
}

// F8: a real basis fixture.  Two unit squares side by side sharing one
// interface, biquadratic, uniformly refined twice, run through the
// gsDofMapperCreator conforming path end to end.
gsMultiBasis<real_t> twoPatchBasis()
{
    gsMultiPatch<real_t> mp = gsNurbsCreator<real_t>::BSplineSquareGrid(2, 1, 1.0);
    gsMultiBasis<real_t> mb(mp);
    mb.degreeElevate(1);
    mb.uniformRefine(2);
    return mb;
}

gsDofMapper creatorTwoPatch()
{
    gsMultiBasis<real_t> mb = twoPatchBasis();
    return createMapper(mb, /*nComp=*/1, /*conforming=*/true, /*finalize=*/true);
}

// F9: a genuinely ragged patch-concatenated mapper, built through the
// per-component ragged constructor.  Component 0: patches of size 5,5
// (total 10).  Component 1: patches of size 2,4 (total 6) -- UNEQUAL to
// component 0's, on every patch.  hasDistinctComponentSpaces is declared
// false: the point of this fixture is the ragged per-component *sizes*,
// independent of the declared-distinct flag.
gsDofMapper raggedPatchMapper()
{
    std::vector<gsVector<index_t> > sz(2);
    sz[0].resize(2); sz[0][0] = 5; sz[0][1] = 5;
    sz[1].resize(2); sz[1][0] = 2; sz[1][1] = 4;
    gsDofMapper m(sz, false);
    m.finalize();
    return m;
}

// F10: a genuinely ragged global-identity/aliased mapper, built through the
// per-component setIdentity overload.  Component 0 total 7, component 1
// total 10 -- UNEQUAL, same motivation as F9 for the aliased layout.
gsDofMapper raggedIdentityMapper()
{
    std::vector<size_t> dofsPerComponent;
    dofsPerComponent.push_back(7);
    dofsPerComponent.push_back(10);
    gsDofMapper m;
    m.setIdentity(3, dofsPerComponent);
    m.finalize();
    return m;
}

// --- the target configuration: the 2D Raviart-Thomas component pair ------
//
// One vector variable whose two components live in different tensor-product
// spline spaces on the same patch and the same mesh, degrees and
// regularities transposed between them:
//
//     component 0 = S^{3,2}_{2,1}      component 1 = S^{2,3}_{1,2}
//
// A 1D space of degree p and regularity r over E elements has dimension
// E(p-r)+r+1, so with p-r==1 in every direction here the component
// dimensions are (E0+3)(E1+2) and (E0+2)(E1+3).  On an ISOTROPIC mesh those
// two numbers coincide (4x4: 42 and 42) and only an anisotropic mesh
// separates them (4x2: 28 and 30).  That is why every fixture below comes in
// both mesh flavours, and why the distinctness of the component spaces has
// to be a declared property: on the isotropic mesh -- the default case, a
// unit square uniformly refined -- an RT mapper is size-indistinguishable
// from an ordinary uniform one, so no predicate built on cardinalities can
// tell them apart.

gsTensorBSplineBasis<2,real_t> rtComponentBasis(short_t p0, short_t p1,
                                                index_t e0, index_t e1)
{
    // Maximal regularity (interior multiplicity p-r == 1) in both directions.
    gsKnotVector<real_t> kv0(0.0, 1.0, e0-1, p0+1, 1, p0);
    gsKnotVector<real_t> kv1(0.0, 1.0, e1-1, p1+1, 1, p1);
    return gsTensorBSplineBasis<2,real_t>(kv0, kv1);
}

// One patch, one size vector per component, sizes taken from the two real
// bases so the dimension arithmetic above is proven rather than asserted.
// hasDistinctComponentSpaces is declared true: the components genuinely come
// from two different basis objects.
gsDofMapper rtMapper(index_t e0, index_t e1, bool declareDistinct = true)
{
    const gsTensorBSplineBasis<2,real_t> b0 = rtComponentBasis(3, 2, e0, e1);
    const gsTensorBSplineBasis<2,real_t> b1 = rtComponentBasis(2, 3, e0, e1);

    std::vector<gsVector<index_t> > sz(2);
    sz[0].resize(1); sz[0][0] = b0.size();
    sz[1].resize(1); sz[1][0] = b1.size();

    gsDofMapper m(sz, declareDistinct);
    m.finalize();
    return m;
}

// F11: the RT pair on an ISOTROPIC 4x4 mesh -- 42 and 42, equal.
gsDofMapper rtIsotropicMapper() { return rtMapper(4, 4); }

// F12: the RT pair on an ANISOTROPIC 4x2 mesh -- 28 and 30, unequal.
gsDofMapper rtAnisotropicMapper() { return rtMapper(4, 2); }

} // anonymous namespace


SUITE(gsDofMapper_test)
{

// =========================================================================
// Default-constructed state
// =========================================================================

// The default-constructed observation: zero components,
// mapSize()==0 and, despite there being no patch data at all,
// numPatches()==1, because the default constructor seeds m_offset with a
// single zero and numPatches() reports m_offset.size().
TEST(default_constructed_state)
{
    const gsDofMapper m;

    CHECK_EQUAL(0, m.numComponents());
    CHECK_EQUAL(0u, (unsigned)m.componentsSize());
    CHECK_EQUAL(0u, (unsigned)m.mapSize());
    CHECK_EQUAL(1u, (unsigned)m.numPatches());
    CHECK(!m.isFinalized());

    // size(), boundarySize() and coupledSize() guard with GISMO_ENSURE, which
    // unlike GISMO_ASSERT, compiled out under NDEBUG throws
    // std::runtime_error in Release builds too.  Hence plain CHECK_THROW and
    // not CHECK_THROW_IN_DEBUG.  The three "Ensure" banners these print on
    // std::cerr are expected output of this test.
    CHECK_THROW(m.size()        , std::runtime_error);
    CHECK_THROW(m.boundarySize(), std::runtime_error);
    CHECK_THROW(m.coupledSize() , std::runtime_error);
}

// =========================================================================
// F1 -- single patch, no coupling, no elimination
// =========================================================================

TEST(single_patch_plain_counts)
{
    const gsDofMapper m = singlePatchPlain();
    PIN("f1.elimdup", "elimdup=0", dumpElimDup(m));
    PIN("f1.counts", "comps=1 ncomp=1 npatch=1 map=6 size=6 free=6 elim=0 cpld=0 tagged=0 allfree=1 perm=1 final=1", dumpCounts(m));
    PIN("f1.percomp", "c0:size=6,free=6,total=6", dumpPerComponent(m));
    PIN("f1.layout", "off=[0] ps=c0:[6]", dumpLayout(m));
    PIN("f1.firstlast", "first0=0 last=6", dumpFirstLast(m));
}

TEST(single_patch_plain_indices)
{
    const gsDofMapper m = singlePatchPlain();
    PIN("f1.asvector", "c0[0,1,2,3,4,5]", dumpAsVector(m));
    PIN("f1.mapindex", "[0,1,2,3,4,5]", dumpMapIndex(m));
    PIN("f1.index", "c0|0,1,2,3,4,5", dumpIndex(m));
    PIN("f1.flags", "FFFFFF", dumpFreeBoundaryFlags(m));
    PIN("f1.bindex", "[]", dumpBindex(m));
    PIN("f1.gflags", "FFFFFF gbi=[]", dumpGlobalFlags(m, 0));
    PIN("f1.findbf", "bnd=[] free=[0,1,2,3,4,5]", dumpFindBoundaryFree(m));
    PIN("f1.onpatch", "0:0 1:1 2:2 3:3 4:4 5:5", dumpIndexOnPatch(m));
}

TEST(single_patch_plain_coupled_queries)
{
    const gsDofMapper m = singlePatchPlain();
    // See three_comp_coupled_queries_per_component for the same digest on a
    // mapper with more than one component.
    PIN("f1.coupled", "flags=...... cidx=[] gflags=...... findCoupled=[] findCoupledPairs=00[] findFreeUncoupled=[0,1,2,3,4,5]", dumpCoupledQueries(m));
}

TEST(single_patch_plain_component_and_preimage)
{
    const gsDofMapper m = singlePatchPlain();
    // componentOf / preImage / anyPreImage are pinned on zero-shift fixtures
    // only: componentOf never subtracts m_shift and preImage subtracts the
    // global shift from a patch-local index.  A later commit normalises
    // shift handling.
    PIN("f1.componentof", "[0,0,0,0,0,0]", dumpComponentOf(m));
    PIN("f1.preimage", "0[(0,0)] 1[(0,1)] 2[(0,2)] 3[(0,3)] 4[(0,4)] 5[(0,5)]", dumpPreImages(m));
    PIN("f1.anypreimage", "[(0,0),(0,1),(0,2),(0,3),(0,4),(0,5)]", dumpAnyPreImage(m));
    PIN("f1.anypreimages", "[(0,0),(0,1),(0,2),(0,3),(0,4),(0,5)]", join(m.anyPreImages(0)));
}

TEST(single_patch_plain_inverses)
{
    const gsDofMapper m = singlePatchPlain();
    PIN("f1.inverseonpatch", "[(0,0),(1,1),(2,2),(3,3),(4,4),(5,5)]",
        dumpInverseOnPatch(m, 0));

    // A single-component permutation: every position of the result is the
    // image of a local dof, so no sentinel is visible here.  See
    // inverse_as_vector_marks_other_components for the sentinel.
    PIN("f1.inverseasvector", "[0,1,2,3,4,5]", join(m.inverseAsVector(0)));
}

// =========================================================================
// F2 -- two patches, coupling, elimination, tagging
// =========================================================================

TEST(two_patch_coupled_elim_counts)
{
    const gsDofMapper m = twoPatchCoupledElim();
    PIN("f2.elimdup", "elimdup=2", dumpElimDup(m));
    PIN("f2.counts", "comps=1 ncomp=1 npatch=2 map=12 size=9 free=7 elim=2 cpld=2 tagged=2 allfree=0 perm=0 final=1", dumpCounts(m));
    PIN("f2.percomp", "c0:size=9,free=7,total=12", dumpPerComponent(m));
    PIN("f2.layout", "off=[0,6] ps=c0:[6,6]", dumpLayout(m));
    PIN("f2.firstlast", "first0=0 last=7", dumpFirstLast(m));
}

TEST(two_patch_coupled_elim_indices)
{
    const gsDofMapper m = twoPatchCoupledElim();
    PIN("f2.asvector", "c0[7,0,1,2,5,6,5,6,6,8,3,4]", dumpAsVector(m));
    PIN("f2.mapindex", "[7,0,1,2,5,6,5,6,6,8,3,4]", dumpMapIndex(m));
    PIN("f2.index", "c0|7,0,1,2,5,6|5,6,6,8,3,4", dumpIndex(m));
    PIN("f2.flags", "BFFFFF|FFFBFF", dumpFreeBoundaryFlags(m));
    PIN("f2.bindex", "[0:0:0->0,0:1:3->1]", dumpBindex(m));
    PIN("f2.gflags", "FFFFFFFBB gbi=[7->0,8->1]", dumpGlobalFlags(m, 0));
    PIN("f2.findbf", "bnd=[0],[3] free=[1,2,3,4,5],[0,1,2,4,5]", dumpFindBoundaryFree(m));
    PIN("f2.onpatch", "0:1/- 1:2/- 2:3/- 3:-/4 4:-/5 5:4/0 6:5/1 7:0/- 8:-/3", dumpIndexOnPatch(m));
}

TEST(two_patch_coupled_elim_coupled_queries)
{
    const gsDofMapper m = twoPatchCoupledElim();
    PIN("f2.coupled", "flags=....CC|CCC... cidx=[0:4->0,0:5->1,1:0->0,1:1->1,1:2->1] gflags=.....CC.. findCoupled=[4,5],[0,1,2] findCoupledPairs=00[],01[4,5],10[0,1,2],11[] findFreeUncoupled=[1,2,3],[4,5]", dumpCoupledQueries(m));
}

TEST(two_patch_coupled_elim_component_and_preimage)
{
    const gsDofMapper m = twoPatchCoupledElim();
    // Zero-shift fixture; see single_patch_plain_component_and_preimage.
    PIN("f2.componentof", "[0,0,0,0,0,0,0,0,0]", dumpComponentOf(m));
    PIN("f2.preimage", "0[(0,1)] 1[(0,2)] 2[(0,3)] 3[(1,4)] 4[(1,5)] 5[(0,4),(1,0)] 6[(0,5),(1,1),(1,2)] 7[(0,0)] 8[(1,3)]", dumpPreImages(m));
    PIN("f2.anypreimage", "[(0,1),(0,2),(0,3),(1,4),(1,5),(0,4),(0,5),(0,0),(1,3)]", dumpAnyPreImage(m));
    PIN("f2.anypreimages", "[(0,1),(0,2),(0,3),(1,4),(1,5),(0,4),(0,5),(0,0),(1,3),(-1,0),(-1,0),(-1,0)]", join(m.anyPreImages(0)));
}

TEST(two_patch_coupled_elim_tagged)
{
    const gsDofMapper m = twoPatchCoupledElim();
    // Zero-shift fixture: tindex searches m_tagged for the unshifted dof
    // value while markTagged inserts the shifted one, so these are pinned on
    // zero-shift fixtures only.  A later commit normalises it.
    PIN("f2.tagged", "tagged=[0,3] n=2 gflags=T..T..... flags=.T....|....T. tindex=2,0,1,1,2,2|2,2,2,2,1,2", dumpTagged(m));
}

// localToGlobal and localToGlobal2 are the assembly entry points and they
// are pinned in their own right, not only transitively through index().
// F2 carries both free and eliminated
// dofs, so the free-from-the-top / boundary-from-the-bottom packing of
// localToGlobal2 is actually exercised.
TEST(two_patch_local_to_global)
{
    const gsDofMapper m = twoPatchCoupledElim();
    PIN("f2.l2g", "k0:6x1[7,0,1,2,5,6] k1:6x1[5,6,6,8,3,4]", dumpLocalToGlobal(m, 0));
    PIN("f2.l2g2", "k0:nfree=5 6x2[(1,0),(2,1),(3,2),(4,5),(5,6),(0,7)] k1:nfree=5 6x2[(0,5),(1,6),(2,6),(4,3),(5,4),(3,8)]", dumpLocalToGlobal2(m, 0));
}

// Pre-existing mainline defect, pinned deliberately so that it is not changed
// by accident: gsDofMapper::findTagged builds the intersection into a local
// std::list and then returns an untouched default-constructed gsVector, so it
// is always empty even when the patch carries tagged dofs.  This is a known,
// pre-existing defect that is deliberately left alone here; no later commit
// is expected to change this expectation.
TEST(find_tagged_returns_empty_defect)
{
    const gsDofMapper m = twoPatchCoupledElim();
    CHECK(m.taggedSize() > 0);            // the fixture really has tagged dofs
    CHECK_EQUAL(0, m.findTagged(0).size());
    CHECK_EQUAL(0, m.findTagged(1).size());
}

// =========================================================================
// F3 -- three components with different per-component patterns
// =========================================================================

TEST(three_comp_uniform_counts)
{
    const gsDofMapper m = threeCompUniform();
    // boundarySizeWithDuplicates counts the eliminated dofs with their
    // multiplicity over patches, so it is bounded below by boundarySize().
    PIN("f3.elimdup", "elimdup=4", dumpElimDup(m));
    PIN("f3.counts", "comps=3 ncomp=3 npatch=2 map=27 size=24 free=20 elim=4 cpld=3 tagged=0 allfree=0 perm=0 final=1", dumpCounts(m));
    PIN("f3.percomp", "c0:size=8,free=7,total=9 c1:size=7,free=5,total=9 c2:size=9,free=8,total=9", dumpPerComponent(m));
    PIN("f3.layout", "off=[0,4] ps=c0:[4,5] c1:[4,5] c2:[4,5]", dumpLayout(m));
    PIN("f3.firstlast", "first0=0 last=20", dumpFirstLast(m));
}

TEST(three_comp_uniform_indices)
{
    const gsDofMapper m = threeCompUniform();
    PIN("f3.asvector", "c0[20,0,1,6,6,2,3,4,5] c1[21,7,10,11,8,10,11,9,22] c2[12,13,14,15,16,17,18,23,19]", dumpAsVector(m));
    PIN("f3.mapindex", "[20,0,1,6,6,2,3,4,5,21,7,10,11,8,10,11,9,22,12,13,14,15,16,17,18,23,19]", dumpMapIndex(m));
    PIN("f3.index", "c0|20,0,1,6|6,2,3,4,5;c1|21,7,10,11|8,10,11,9,22;c2|12,13,14,15|16,17,18,23,19", dumpIndex(m));
    PIN("f3.flags", "BFFF|FFFFF;BFFF|FFFFB;FFFF|FFFBF", dumpFreeBoundaryFlags(m));
    PIN("f3.bindex", "[0:0:0->0,1:0:0->1,1:1:4->2,2:1:3->3]", dumpBindex(m));
    PIN("f3.gflags", "FFFFFFFFFFFFFFFFFFFFBBBB gbi=[20->0,21->1,22->2,23->3]", dumpGlobalFlags(m, 0));
    PIN("f3.findbf", "bnd=[0],[] free=[1,2,3],[0,1,2,3,4]", dumpFindBoundaryFree(m));
    PIN("f3.onpatch", "0:1/- 1:2/- 2:-/1 3:-/2 4:-/3 5:-/4 6:3/0 7:1/- 8:-/0 9:-/3 10:2/1 11:3/2 12:0/- 13:1/- 14:2/- 15:3/- 16:-/0 17:-/1 18:-/2 19:-/4 20:0/- 21:0/- 22:-/4 23:-/3", dumpIndexOnPatch(m));
}

TEST(three_comp_uniform_component_and_preimage)
{
    const gsDofMapper m = threeCompUniform();
    // Zero-shift fixture; see single_patch_plain_component_and_preimage.
    PIN("f3.componentof", "[0,0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2,2,2,2,0,1,1,2]", dumpComponentOf(m));
    PIN("f3.preimage", "0[(0,1)] 1[(0,2)] 2[(1,1)] 3[(1,2)] 4[(1,3)] 5[(1,4)] 6[(0,3),(1,0)] 7[(0,1)] 8[(1,0)] 9[(1,3)] 10[(0,2),(1,1)] 11[(0,3),(1,2)] 12[(0,0)] 13[(0,1)] 14[(0,2)] 15[(0,3)] 16[(1,0)] 17[(1,1)] 18[(1,2)] 19[(1,4)] 20[(0,0)] 21[(0,0)] 22[(1,4)] 23[(1,3)]", dumpPreImages(m));
    PIN("f3.anypreimage", "[(0,1),(0,2),(1,1),(1,2),(1,3),(1,4),(0,3),(0,1),(1,0),(1,3),(0,2),(0,3),(0,0),(0,1),(0,2),(0,3),(1,0),(1,1),(1,2),(1,4),(0,0),(0,0),(1,4),(1,3)]", dumpAnyPreImage(m));
    // See any_pre_images_agrees_with_any_pre_image for anyPreImages(c) on
    // this fixture; it is checked against anyPreImage rather than pinned as
    // a literal.
    PIN("f3.tagged", "tagged=[] n=0 gflags=........................ flags=....|.....;....|.....;....|..... tindex=0,0,0,0|0,0,0,0,0;0,0,0,0|0,0,0,0,0;0,0,0,0|0,0,0,0,0", dumpTagged(m));
}

// =========================================================================
// F4 -- F3 with a global and a boundary shift
// =========================================================================

// Only the shift behaviours that must not change are pinned on the shifted
// fixture: asVector (which carries m_shift), index, bindex, global_to_bindex,
// is_free_index, is_boundary_index, firstIndex(0), lastIndex() and the sizes.
// componentOf, preImage, anyPreImage, anyPreImages, tindex, is_tagged and
// is_tagged_index all mishandle m_shift today (componentOf never subtracts it,
// preImage subtracts a global shift from a patch-local index, tindex searches
// unshifted values while markTagged inserts shifted ones) and a later commit
// normalises shift handling, so they are deliberately not pinned here.
TEST(three_comp_shifted)
{
    const gsDofMapper m = threeCompShifted();
    // See f3.elimdup: same fixture, and the count is taken on the stored
    // (unshifted) values, so the shift does not enter it.
    PIN("f4.elimdup", "elimdup=4", dumpElimDup(m));
    PIN("f4.counts", "comps=3 ncomp=3 npatch=2 map=27 size=24 free=20 elim=4 cpld=3 tagged=0 allfree=0 perm=0 final=1", dumpCounts(m));
    PIN("f4.percomp", "c0:size=8,free=7,total=9 c1:size=7,free=5,total=9 c2:size=9,free=8,total=9", dumpPerComponent(m));
    PIN("f4.layout", "off=[0,4] ps=c0:[4,5] c1:[4,5] c2:[4,5]", dumpLayout(m));
    PIN("f4.firstlast", "first0=100 last=120", dumpFirstLast(m));   // firstIndex(0) == m_shift
    PIN("f4.asvector", "c0[120,100,101,106,106,102,103,104,105] c1[121,107,110,111,108,110,111,109,122] c2[112,113,114,115,116,117,118,123,119]", dumpAsVector(m));
    // freeIndex(i,k,c) returns the index WITHOUT m_shift; read against
    // f4.index just below, this literal is the pin on that distinction.
    PIN("f4.freeindex", "c0|20,0,1,6|6,2,3,4,5;c1|21,7,10,11|8,10,11,9,22;c2|12,13,14,15|16,17,18,23,19", dumpFreeIndex(m));
    PIN("f4.index", "c0|120,100,101,106|106,102,103,104,105;c1|121,107,110,111|108,110,111,109,122;c2|112,113,114,115|116,117,118,123,119", dumpIndex(m));
    PIN("f4.bindex", "[0:0:0->7,1:0:0->8,1:1:4->9,2:1:3->10]", dumpBindex(m));
    PIN("f4.gflags", "FFFFFFFFFFFFFFFFFFFFBBBB gbi=[120->7,121->8,122->9,123->10]", dumpGlobalFlags(m, 100));
    // indexOnPatch is pinned on every fixture.  On this one the digest is fed
    // UNSHIFTED indices on purpose: indexOnPatch ignores m_shift entirely --
    // it compares gl against the stored, unshifted dof values and dispatches
    // through componentOf, which never subtracts the shift -- so a shifted
    // global index finds nothing today.
    PIN("f4.onpatch", "0:1/- 1:2/- 2:-/1 3:-/2 4:-/3 5:-/4 6:3/0 7:1/- 8:-/0 9:-/3 10:2/1 11:3/2 12:0/- 13:1/- 14:2/- 15:3/- 16:-/0 17:-/1 18:-/2 19:-/4 20:0/- 21:0/- 22:-/4 23:-/3", dumpIndexOnPatch(m));
}

// =========================================================================
// F5 -- identity / aliased layout
// =========================================================================

// UPDATED: gsDofMapper used to model the global-identity/aliased layout
// that setIdentity() produces by leaving every patch offset at zero and
// letting only the LAST patch's sentinel carry the component's dof total;
// patchSize(p,c) therefore reported 0 for every patch except the last, and
// every API built on top of it (index, indexOnPatch, findFree, findBoundary,
// preImage/anyPreImage, is_free/is_boundary flags) only ever "saw" the
// aliased dofs through that one last patch.
//
// The aliased layout is now defined explicitly instead of falling out of a
// coincidental all-zero offset pattern: patchSize(p,c) is now the
// component-global identity total for EVERY patch, offset(p,c) stays zero
// for every real patch, and preImage/anyPreImage canonically report patch 0
// (rather than whichever patch happened to hold the sentinel) as the stored
// preimage. The eight pins below are exactly the ones that observe
// patch-dependent aliasing behaviour and therefore change under that
// redefinition:
//
// - f5.layout / f5.index / f5.flags / f5.findbf / f5.onpatch: every patch
//   now reports the full 7-entry identity range instead of only the last;
// - f5.preimage / f5.anypreimage: the reported patch is now 0 (canonical),
//   not 2 (the old "last patch holds the sentinel" artifact);
// - f5.tagged: its is_tagged/tindex columns are derived from patchSize per
//   patch (via dumpTagged's per-(component,patch) loop), so they follow the
//   same three-patches-worth-of-output change as f5.flags, even though no
//   dof is actually tagged in this fixture.
//
// f5.counts, f5.percomp, f5.firstlast, f5.asvector, f5.mapindex,
// f5.componentof are NOT in this list: they are computed directly from
// per-component totals/values, never from the per-patch offset pattern, so
// they stay byte-identical.
TEST(identity_mapper)
{
    const gsDofMapper m = identityMapper();
    // boundarySizeWithDuplicates counts the eliminated dofs with their
    // multiplicity over patches, so it is bounded below by boundarySize().
    PIN("f5.elimdup", "elimdup=0", dumpElimDup(m));
    PIN("f5.counts", "comps=2 ncomp=2 npatch=3 map=14 size=14 free=14 elim=0 cpld=0 tagged=0 allfree=1 perm=1 final=1", dumpCounts(m));
    PIN("f5.percomp", "c0:size=7,free=7,total=7 c1:size=7,free=7,total=7", dumpPerComponent(m));
    PIN("f5.layout", "off=[0,0,0] ps=c0:[7,7,7] c1:[7,7,7]", dumpLayout(m));
    PIN("f5.firstlast", "first0=0 last=14", dumpFirstLast(m));
    PIN("f5.asvector", "c0[0,1,2,3,4,5,6] c1[7,8,9,10,11,12,13]", dumpAsVector(m));
    PIN("f5.mapindex", "[0,1,2,3,4,5,6,7,8,9,10,11,12,13]", dumpMapIndex(m));
    PIN("f5.index", "c0|0,1,2,3,4,5,6|0,1,2,3,4,5,6|0,1,2,3,4,5,6;c1|7,8,9,10,11,12,13|7,8,9,10,11,12,13|7,8,9,10,11,12,13", dumpIndex(m));
    PIN("f5.flags", "FFFFFFF|FFFFFFF|FFFFFFF;FFFFFFF|FFFFFFF|FFFFFFF", dumpFreeBoundaryFlags(m));
    PIN("f5.bindex", "[]", dumpBindex(m));
    PIN("f5.gflags", "FFFFFFFFFFFFFF gbi=[]", dumpGlobalFlags(m, 0));
    PIN("f5.findbf", "bnd=[],[],[] free=[0,1,2,3,4,5,6],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6]", dumpFindBoundaryFree(m));
    PIN("f5.onpatch", "0:0/0/0 1:1/1/1 2:2/2/2 3:3/3/3 4:4/4/4 5:5/5/5 6:6/6/6 7:0/0/0 8:1/1/1 9:2/2/2 10:3/3/3 11:4/4/4 12:5/5/5 13:6/6/6", dumpIndexOnPatch(m));
    PIN("f5.componentof", "[0,0,0,0,0,0,0,1,1,1,1,1,1,1]", dumpComponentOf(m));
    PIN("f5.preimage", "0[(0,0)] 1[(0,1)] 2[(0,2)] 3[(0,3)] 4[(0,4)] 5[(0,5)] 6[(0,6)] 7[(0,0)] 8[(0,1)] 9[(0,2)] 10[(0,3)] 11[(0,4)] 12[(0,5)] 13[(0,6)]", dumpPreImages(m));
    PIN("f5.anypreimage", "[(0,0),(0,1),(0,2),(0,3),(0,4),(0,5),(0,6),(0,0),(0,1),(0,2),(0,3),(0,4),(0,5),(0,6)]", dumpAnyPreImage(m));
    PIN("f5.tagged", "tagged=[] n=0 gflags=.............. flags=.......|.......|.......;.......|.......|....... tindex=0,0,0,0,0,0,0|0,0,0,0,0,0,0|0,0,0,0,0,0,0;0,0,0,0,0,0,0|0,0,0,0,0,0,0|0,0,0,0,0,0,0", dumpTagged(m));
}

// =========================================================================
// F6 -- F3 with markCoupledAsTagged and a permuted component-0 free block
// =========================================================================

// The cpld=2 in f6.counts records the corrected permuteFreeDofs bookkeeping.
// Permuting a component destroys the ability to track ITS coupled dofs, so
// that component's own coupled count drops to zero and every later
// cumulative prefix loses exactly that count: F3 has coupled counts 1, 2, 0
// per component (cumulative 1, 3, 3), so permuting component 0 leaves
// cumulative 0, 2, 2 and coupledSize() == 2 -- component 1's two coupled
// dofs are still tracked.  The earlier revision applied "*s += (*s-1)"
// (i.e. *s = 2*(*s)-1) here and reported 5, i.e. MORE coupled dofs than
// before the permutation.  The remaining f6 values are ordinary pins.
//
// f6.tagged is the composition of the two tag operations, both corrected.
// markCoupledAsTagged tags F3's real coupled dofs, 6, 10 and 11; permuting
// component 0 then moves the one inside that component's free block [0,7),
// 6 -> perm[6] == 4, and leaves 10 and 11 -- which belong to component 1 --
// where they are.  Both halves used to be wrong and used to cancel: the tags
// were computed as m_numFreeDofs[c+1]+m_numElimDofs[c]+i, a set disjoint
// from the coupled dofs whose last entries ran past size() altogether, and
// permuteFreeDofs then rebuilt m_tagged by walking only the permuted
// component's storage, deleting every one of them.  The list came out empty,
// which is why neither defect was visible here.  See
// mark_coupled_as_tagged_tags_the_coupled_dofs and
// permute_free_dofs_keeps_other_components_tags.
TEST(permuted_mapper)
{
    const gsDofMapper m = permutedMapper();
    // boundarySizeWithDuplicates counts the eliminated dofs with their
    // multiplicity over patches, so it is bounded below by boundarySize().
    PIN("f6.elimdup", "elimdup=4", dumpElimDup(m));
    PIN("f6.counts", "comps=3 ncomp=3 npatch=2 map=27 size=24 free=20 elim=4 cpld=2 tagged=3 allfree=0 perm=0 final=1", dumpCounts(m));
    PIN("f6.percomp", "c0:size=8,free=7,total=9 c1:size=7,free=5,total=9 c2:size=9,free=8,total=9", dumpPerComponent(m));
    PIN("f6.layout", "off=[0,4] ps=c0:[4,5] c1:[4,5] c2:[4,5]", dumpLayout(m));
    PIN("f6.firstlast", "first0=0 last=20", dumpFirstLast(m));
    PIN("f6.asvector", "c0[20,3,0,4,4,6,1,5,2] c1[21,7,10,11,8,10,11,9,22] c2[12,13,14,15,16,17,18,23,19]", dumpAsVector(m));
    PIN("f6.mapindex", "[20,3,0,4,4,6,1,5,2,21,7,10,11,8,10,11,9,22,12,13,14,15,16,17,18,23,19]", dumpMapIndex(m));
    PIN("f6.index", "c0|20,3,0,4|4,6,1,5,2;c1|21,7,10,11|8,10,11,9,22;c2|12,13,14,15|16,17,18,23,19", dumpIndex(m));
    PIN("f6.flags", "BFFF|FFFFF;BFFF|FFFFB;FFFF|FFFBF", dumpFreeBoundaryFlags(m));
    PIN("f6.bindex", "[0:0:0->0,1:0:0->1,1:1:4->2,2:1:3->3]", dumpBindex(m));
    PIN("f6.gflags", "FFFFFFFFFFFFFFFFFFFFBBBB gbi=[20->0,21->1,22->2,23->3]", dumpGlobalFlags(m, 0));
    PIN("f6.findbf", "bnd=[0],[] free=[1,2,3],[0,1,2,3,4]", dumpFindBoundaryFree(m));
    PIN("f6.onpatch", "0:2/- 1:-/2 2:-/4 3:1/- 4:3/0 5:-/3 6:-/1 7:1/- 8:-/0 9:-/3 10:2/1 11:3/2 12:0/- 13:1/- 14:2/- 15:3/- 16:-/0 17:-/1 18:-/2 19:-/4 20:0/- 21:0/- 22:-/4 23:-/3", dumpIndexOnPatch(m));
    PIN("f6.componentof", "[0,0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2,2,2,2,0,1,1,2]", dumpComponentOf(m));
    PIN("f6.preimage", "0[(0,2)] 1[(1,2)] 2[(1,4)] 3[(0,1)] 4[(0,3),(1,0)] 5[(1,3)] 6[(1,1)] 7[(0,1)] 8[(1,0)] 9[(1,3)] 10[(0,2),(1,1)] 11[(0,3),(1,2)] 12[(0,0)] 13[(0,1)] 14[(0,2)] 15[(0,3)] 16[(1,0)] 17[(1,1)] 18[(1,2)] 19[(1,4)] 20[(0,0)] 21[(0,0)] 22[(1,4)] 23[(1,3)]", dumpPreImages(m));
    PIN("f6.anypreimage", "[(0,2),(1,2),(1,4),(0,1),(0,3),(1,3),(1,1),(0,1),(1,0),(1,3),(0,2),(0,3),(0,0),(0,1),(0,2),(0,3),(1,0),(1,1),(1,2),(1,4),(0,0),(0,0),(1,4),(1,3)]", dumpAnyPreImage(m));
    PIN("f6.tagged", "tagged=[4,10,11] n=3 gflags=....T.....TT............ flags=...T|T....;..TT|.TT..;....|..... tindex=3,0,0,0|0,1,0,1,0;3,1,1,2|1,1,2,1,3;3,3,3,3|3,3,3,3,3", dumpTagged(m));
}

// =========================================================================
// F7 -- collapseDofs
// =========================================================================

TEST(collapsed_mapper)
{
    const gsDofMapper m = collapsedMapper();
    PIN("f7.elimdup", "elimdup=0", dumpElimDup(m));
    PIN("f7.counts", "comps=1 ncomp=1 npatch=2 map=10 size=8 free=8 elim=0 cpld=1 tagged=0 allfree=1 perm=0 final=1", dumpCounts(m));
    PIN("f7.percomp", "c0:size=8,free=8,total=10", dumpPerComponent(m));
    PIN("f7.layout", "off=[0,5] ps=c0:[5,5]", dumpLayout(m));
    PIN("f7.firstlast", "first0=0 last=8", dumpFirstLast(m));
    PIN("f7.asvector", "c0[7,0,7,1,7,2,3,4,5,6]", dumpAsVector(m));
    PIN("f7.mapindex", "[7,0,7,1,7,2,3,4,5,6]", dumpMapIndex(m));
    PIN("f7.index", "c0|7,0,7,1,7|2,3,4,5,6", dumpIndex(m));
    PIN("f7.flags", "FFFFF|FFFFF", dumpFreeBoundaryFlags(m));
    PIN("f7.bindex", "[]", dumpBindex(m));
    PIN("f7.gflags", "FFFFFFFF gbi=[]", dumpGlobalFlags(m, 0));
    PIN("f7.findbf", "bnd=[],[] free=[0,1,2,3,4],[0,1,2,3,4]", dumpFindBoundaryFree(m));
    PIN("f7.onpatch", "0:1/- 1:3/- 2:-/0 3:-/1 4:-/2 5:-/3 6:-/4 7:0/-", dumpIndexOnPatch(m));
    PIN("f7.coupled", "flags=C.C.C|..... cidx=[0:0->0,0:2->0,0:4->0] gflags=.......C findCoupled=[0,2,4],[] findCoupledPairs=00[],01[],10[],11[] findFreeUncoupled=[1,3],[0,1,2,3,4]", dumpCoupledQueries(m));
    // Zero-shift fixture; see single_patch_plain_component_and_preimage.
    PIN("f7.componentof", "[0,0,0,0,0,0,0,0]", dumpComponentOf(m));
    PIN("f7.preimage", "0[(0,1)] 1[(0,3)] 2[(1,0)] 3[(1,1)] 4[(1,2)] 5[(1,3)] 6[(1,4)] 7[(0,0),(0,2),(0,4)]", dumpPreImages(m));
    PIN("f7.anypreimage", "[(0,1),(0,3),(1,0),(1,1),(1,2),(1,3),(1,4),(0,0)]", dumpAnyPreImage(m));
    PIN("f7.anypreimages", "[(0,1),(0,3),(1,0),(1,1),(1,2),(1,3),(1,4),(0,0),(-1,0),(-1,0)]", join(m.anyPreImages(0)));
    PIN("f7.tagged", "tagged=[] n=0 gflags=........ flags=.....|..... tindex=0,0,0,0,0|0,0,0,0,0", dumpTagged(m));
}

// =========================================================================
// F8 -- the gsDofMapperCreator path on a real two-patch basis
// =========================================================================

TEST(creator_two_patch_counts)
{
    const gsDofMapper m = creatorTwoPatch();
    PIN("f8.elimdup", "elimdup=0", dumpElimDup(m));
    PIN("f8.counts", "comps=1 ncomp=1 npatch=2 map=50 size=45 free=45 elim=0 cpld=5 tagged=0 allfree=1 perm=0 final=1", dumpCounts(m));
    PIN("f8.percomp", "c0:size=45,free=45,total=50", dumpPerComponent(m));
    PIN("f8.layout", "off=[0,25] ps=c0:[25,25]", dumpLayout(m));
    PIN("f8.firstlast", "first0=0 last=45", dumpFirstLast(m));
}

TEST(creator_two_patch_indices)
{
    const gsDofMapper m = creatorTwoPatch();
    PIN("f8.asvector", "c0[0,1,2,3,40,4,5,6,7,41,8,9,10,11,42,12,13,14,15,43,16,17,18,19,44,40,20,21,22,23,41,24,25,26,27,42,28,29,30,31,43,32,33,34,35,44,36,37,38,39]", dumpAsVector(m));
    PIN("f8.mapindex", "[0,1,2,3,40,4,5,6,7,41,8,9,10,11,42,12,13,14,15,43,16,17,18,19,44,40,20,21,22,23,41,24,25,26,27,42,28,29,30,31,43,32,33,34,35,44,36,37,38,39]", dumpMapIndex(m));
    PIN("f8.index", "c0|0,1,2,3,40,4,5,6,7,41,8,9,10,11,42,12,13,14,15,43,16,17,18,19,44|40,20,21,22,23,41,24,25,26,27,42,28,29,30,31,43,32,33,34,35,44,36,37,38,39", dumpIndex(m));
    PIN("f8.flags", "FFFFFFFFFFFFFFFFFFFFFFFFF|FFFFFFFFFFFFFFFFFFFFFFFFF", dumpFreeBoundaryFlags(m));
    PIN("f8.bindex", "[]", dumpBindex(m));
    PIN("f8.gflags", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF gbi=[]", dumpGlobalFlags(m, 0));
    PIN("f8.findbf", "bnd=[],[] free=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]", dumpFindBoundaryFree(m));
    PIN("f8.onpatch", "0:0/- 1:1/- 2:2/- 3:3/- 4:5/- 5:6/- 6:7/- 7:8/- 8:10/- 9:11/- 10:12/- 11:13/- 12:15/- 13:16/- 14:17/- 15:18/- 16:20/- 17:21/- 18:22/- 19:23/- 20:-/1 21:-/2 22:-/3 23:-/4 24:-/6 25:-/7 26:-/8 27:-/9 28:-/11 29:-/12 30:-/13 31:-/14 32:-/16 33:-/17 34:-/18 35:-/19 36:-/21 37:-/22 38:-/23 39:-/24 40:4/0 41:9/5 42:14/10 43:19/15 44:24/20", dumpIndexOnPatch(m));
}

TEST(creator_two_patch_coupled_queries)
{
    const gsDofMapper m = creatorTwoPatch();
    PIN("f8.coupled", "flags=....C....C....C....C....C|C....C....C....C....C.... cidx=[0:4->0,0:9->1,0:14->2,0:19->3,0:24->4,1:0->0,1:5->1,1:10->2,1:15->3,1:20->4] gflags=........................................CCCCC findCoupled=[4,9,14,19,24],[0,5,10,15,20] findCoupledPairs=00[],01[4,9,14,19,24],10[0,5,10,15,20],11[] findFreeUncoupled=[0,1,2,3,5,6,7,8,10,11,12,13,15,16,17,18,20,21,22,23],[1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,21,22,23,24]", dumpCoupledQueries(m));
}

TEST(creator_two_patch_component_and_preimage)
{
    const gsDofMapper m = creatorTwoPatch();
    // Zero-shift fixture; see single_patch_plain_component_and_preimage.
    PIN("f8.componentof", "[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]", dumpComponentOf(m));
    PIN("f8.preimage", "0[(0,0)] 1[(0,1)] 2[(0,2)] 3[(0,3)] 4[(0,5)] 5[(0,6)] 6[(0,7)] 7[(0,8)] 8[(0,10)] 9[(0,11)] 10[(0,12)] 11[(0,13)] 12[(0,15)] 13[(0,16)] 14[(0,17)] 15[(0,18)] 16[(0,20)] 17[(0,21)] 18[(0,22)] 19[(0,23)] 20[(1,1)] 21[(1,2)] 22[(1,3)] 23[(1,4)] 24[(1,6)] 25[(1,7)] 26[(1,8)] 27[(1,9)] 28[(1,11)] 29[(1,12)] 30[(1,13)] 31[(1,14)] 32[(1,16)] 33[(1,17)] 34[(1,18)] 35[(1,19)] 36[(1,21)] 37[(1,22)] 38[(1,23)] 39[(1,24)] 40[(0,4),(1,0)] 41[(0,9),(1,5)] 42[(0,14),(1,10)] 43[(0,19),(1,15)] 44[(0,24),(1,20)]", dumpPreImages(m));
    PIN("f8.anypreimage", "[(0,0),(0,1),(0,2),(0,3),(0,5),(0,6),(0,7),(0,8),(0,10),(0,11),(0,12),(0,13),(0,15),(0,16),(0,17),(0,18),(0,20),(0,21),(0,22),(0,23),(1,1),(1,2),(1,3),(1,4),(1,6),(1,7),(1,8),(1,9),(1,11),(1,12),(1,13),(1,14),(1,16),(1,17),(1,18),(1,19),(1,21),(1,22),(1,23),(1,24),(0,4),(0,9),(0,14),(0,19),(0,24)]", dumpAnyPreImage(m));
    PIN("f8.anypreimages", "[(0,0),(0,1),(0,2),(0,3),(0,5),(0,6),(0,7),(0,8),(0,10),(0,11),(0,12),(0,13),(0,15),(0,16),(0,17),(0,18),(0,20),(0,21),(0,22),(0,23),(1,1),(1,2),(1,3),(1,4),(1,6),(1,7),(1,8),(1,9),(1,11),(1,12),(1,13),(1,14),(1,16),(1,17),(1,18),(1,19),(1,21),(1,22),(1,23),(1,24),(0,4),(0,9),(0,14),(0,19),(0,24),(-1,0),(-1,0),(-1,0),(-1,0),(-1,0)]", join(m.anyPreImages(0)));
}

// addShift adds to the current shift instead of replacing it, so after
// setShift(100) + addShift(5) the global numbering starts at 105.
TEST(add_shift_accumulates)
{
    gsDofMapper m = threeCompUniform();
    m.setShift(100);
    m.addShift(5);
    PIN("shift.accumulates", "first0=105 last=125", dumpFirstLast(m));
}

// =========================================================================
// Independent numbering oracle
// =========================================================================

// For an uncoupled, uneliminated, patch-concatenated multi-component mapper
// the finalized numbering is component-major:
//     index(i,p,c) == sum_{c'<c} totalSize(c') + offset(p) + i.
// This is not a recorded literal: it is an independent check on the
// component-major numbering that any reimplementation must keep satisfying.
TEST(component_major_numbering_oracle)
{
    gsVector<index_t> sz(2);
    sz[0] = 3; sz[1] = 4;
    gsDofMapper m(sz, 2);
    m.finalize();

    CHECK_EQUAL(0, m.boundarySize());
    CHECK_EQUAL(0, m.coupledSize());
    CHECK_EQUAL(14, m.size());

    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        index_t base = 0;
        for (index_t cp = 0; cp != c; ++cp)
            base += static_cast<index_t>(m.totalSize(cp));

        for (index_t p = 0; p != nPatches(m); ++p)
        {
            const index_t n = static_cast<index_t>(m.patchSize(p, c));
            for (index_t i = 0; i != n; ++i)
                CHECK_EQUAL(base + static_cast<index_t>(m.offset(p)) + i,
                            m.index(i, p, c));
        }
    }
}

// =========================================================================
// F9/F10 -- genuinely ragged mappers (unequal per-component sizes)
// =========================================================================
//
// Regression tests for a bug found by review: indexOnPatch() computed its
// search-window end from patchSize(k) -- i.e. patchSize(k,0), component 0's
// size, regardless of which component the queried global dof actually
// belongs to.  Every other fixture in this file that has more than one
// component (F3/F4/F6 = threeCompUniform() and its derivatives, F5 =
// identityMapper()) happens to have EQUAL per-component sizes -- only the
// coupling/elimination *pattern* differs -- so none of them could have
// caught this: the bug is only reachable once component sizes genuinely
// differ, which the ragged constructor and the per-component setIdentity
// overload now make possible.  Any code that assumes equal component sizes
// -- whether a compatibility check or, as here, a query's own bookkeeping --
// is exactly the kind of assumption this class must no longer make.

TEST(ragged_patch_indexOnPatch)
{
    const gsDofMapper m = raggedPatchMapper();
    CHECK_EQUAL(2u, (unsigned)m.componentsSize());
    CHECK_EQUAL(5u, (unsigned)m.patchSize(0,0));
    CHECK_EQUAL(5u, (unsigned)m.patchSize(1,0));
    CHECK_EQUAL(2u, (unsigned)m.patchSize(0,1));
    CHECK_EQUAL(4u, (unsigned)m.patchSize(1,1));

    // Global numbering (uncoupled, no elimination, component-major order):
    // component 0 first (patch0 local0-4 -> global0-4,
    // patch1 local0-4 -> global5-9), then component 1 (patch0 local0-1 ->
    // global10-11, patch1 local0-3 -> global12-15).
    index_t local = -12345;

    CHECK(m.indexOnPatch(10, 0, local));
    CHECK_EQUAL(0, local);
    CHECK(!m.indexOnPatch(10, 1, local));

    CHECK(m.indexOnPatch(11, 0, local));
    CHECK_EQUAL(1, local);
    CHECK(!m.indexOnPatch(11, 1, local));

    // Component 1, patch 1, local 0..3 -> global 12..15.  Before the fix,
    // the search window on patch 0 was [0, patchSize(0,0)) == [0,5), and on
    // patch 1 was [offAt(1,1), offAt(1,1)+patchSize(1,0)) ==
    // component 1's own patch-1 data mis-bounded by component 0's patch-1
    // size (5) instead of component 1's own (4) -- both wrong in different
    // ways.  With the fix, each of these must be found on patch 1 only.
    for (index_t loc = 0; loc != 4; ++loc)
    {
        CHECK(!m.indexOnPatch(12+loc, 0, local));
        CHECK(m.indexOnPatch(12+loc, 1, local));
        CHECK_EQUAL(loc, local);
    }
}

TEST(ragged_identity_indexOnPatch)
{
    const gsDofMapper m = raggedIdentityMapper();
    CHECK_EQUAL(2u, (unsigned)m.componentsSize());
    CHECK(gsDofMapper::GlobalIdentity == m.layout());
    CHECK_EQUAL(7u,  (unsigned)m.totalSize(0));
    CHECK_EQUAL(10u, (unsigned)m.totalSize(1));

    // Component 1, local index 7 (global 14) is beyond component 0's total
    // (7) dofs.  Before the fix, indexOnPatch's search window was
    // truncated to patchSize(k,0)==7 regardless of the queried dof's actual
    // component, so this was a false negative on every patch.  Aliased
    // layout: must be found -- with the SAME local index -- on every patch.
    index_t local = -12345;
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        CHECK(m.indexOnPatch(14, k, local));
        CHECK_EQUAL(7, local);
    }

    // Sanity: component 0's own range is unaffected by the fix (it was
    // never ragged relative to itself).
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        CHECK(m.indexOnPatch(0, k, local));
        CHECK_EQUAL(0, local);
    }
}


// =========================================================================
// F11/F12 -- the Raviart-Thomas pair, and the declared-distinctness contract
// =========================================================================

// Pins the dimension table this whole feature turns on: on an isotropic mesh the
// two RT component spaces have exactly the same dimension, and only an
// anisotropic mesh separates them.  If this ever stops holding, the fixtures
// below stop testing what they claim to test.
TEST(rt_component_dimensions)
{
    CHECK_EQUAL(42, rtComponentBasis(3, 2, 4, 4).size());
    CHECK_EQUAL(42, rtComponentBasis(2, 3, 4, 4).size());

    CHECK_EQUAL(28, rtComponentBasis(3, 2, 4, 2).size());
    CHECK_EQUAL(30, rtComponentBasis(2, 3, 4, 2).size());
}

// The single most important test in this file.  An isotropic-mesh RT mapper
// has identical per-patch cardinalities in both components, so every
// size-based predicate reports it "uniform" -- and the uniform evaluator
// would then assemble it with component 0's basis replicated, silently and
// with wrong results, on precisely the configuration this feature exists
// for.  The rejection must therefore come from the declared flag alone.
TEST(rt_isotropic_rejected_on_the_declared_flag_alone)
{
    const gsDofMapper m = rtIsotropicMapper();

    // Size-blind: nothing observable about the storage distinguishes this
    // mapper from an ordinary uniform two-component one.
    CHECK_EQUAL(2u, (unsigned)m.componentsSize());
    CHECK_EQUAL(42u, (unsigned)m.patchSize(0,0));
    CHECK_EQUAL(42u, (unsigned)m.patchSize(0,1));
    CHECK_EQUAL(m.patchSize(0,0), m.patchSize(0,1));
    CHECK_EQUAL(m.totalSize(0), m.totalSize(1));

    CHECK(m.hasDistinctComponentSpaces());
    CHECK(!m.usableByUniformEvaluator());

    // Control: the very same storage shape, declared NOT distinct, is
    // accepted.  The two mappers are observably identical apart from the
    // declaration, which is what proves the rejection is not size-based.
    const gsDofMapper u = rtMapper(4, 4, /*declareDistinct=*/false);
    CHECK_EQUAL(m.patchSize(0,0), u.patchSize(0,0));
    CHECK_EQUAL(m.patchSize(0,1), u.patchSize(0,1));
    CHECK(!u.hasDistinctComponentSpaces());
    CHECK(u.usableByUniformEvaluator());
}

// The anisotropic mesh is rejected twice over: by the declared flag, and --
// independently -- by the cardinality conjunct, which is what a mapper built
// from unequal component sizes trips even when nothing was declared.
TEST(rt_anisotropic_rejected_on_flag_and_on_cardinality)
{
    const gsDofMapper m = rtAnisotropicMapper();
    CHECK_EQUAL(28u, (unsigned)m.patchSize(0,0));
    CHECK_EQUAL(30u, (unsigned)m.patchSize(0,1));
    CHECK(m.hasDistinctComponentSpaces());
    CHECK(!m.usableByUniformEvaluator());

    const gsDofMapper u = rtMapper(4, 2, /*declareDistinct=*/false);
    CHECK(!u.hasDistinctComponentSpaces());
    CHECK(!u.usableByUniformEvaluator()); // rejected by cardinality alone
}

// The full truth table of the compatibility predicate over every fixture in
// this file.  Everything the current mainline builds must stay accepted --
// including a default-constructed mapper, which is the normal pre-init state
// the legacy boundary sees and must not fire on.
TEST(usable_by_uniform_evaluator_truth_table)
{
    const gsDofMapper empty;
    CHECK(!empty.hasDistinctComponentSpaces());
    CHECK(empty.usableByUniformEvaluator());

    CHECK(singlePatchPlain()    .usableByUniformEvaluator()); // 1 component
    CHECK(twoPatchCoupledElim() .usableByUniformEvaluator()); // 1 component
    CHECK(threeCompUniform()    .usableByUniformEvaluator()); // 3 equal comps
    CHECK(identityMapper()      .usableByUniformEvaluator()); // uniform alias
    CHECK(creatorTwoPatch()     .usableByUniformEvaluator()); // creator-built

    // None of the mainline paths declares distinctness.
    CHECK(!singlePatchPlain()   .hasDistinctComponentSpaces());
    CHECK(!threeCompUniform()   .hasDistinctComponentSpaces());
    CHECK(!identityMapper()     .hasDistinctComponentSpaces());
    CHECK(!creatorTwoPatch()    .hasDistinctComponentSpaces());

    // Ragged cardinalities are rejected under either layout.
    CHECK(!raggedPatchMapper()   .usableByUniformEvaluator());
    CHECK(!raggedIdentityMapper().usableByUniformEvaluator());
}

// A mapper whose components have equal totals but a different per-patch
// split is uniform by every total-size measure and still unusable: the
// cardinality conjunct is per patch, not per component total.
TEST(usable_by_uniform_evaluator_is_per_patch)
{
    std::vector<gsVector<index_t> > sz(2);
    sz[0].resize(2); sz[0][0] = 4; sz[0][1] = 6;
    sz[1].resize(2); sz[1][0] = 6; sz[1][1] = 4;
    gsDofMapper m(sz, /*hasDistinctComponentSpaces=*/false);
    m.finalize();

    CHECK_EQUAL(m.totalSize(0), m.totalSize(1)); // 10 == 10
    CHECK(!m.usableByUniformEvaluator());
}

// =========================================================================
// Metadata carried through swap
// =========================================================================

TEST(swap_carries_layout_metadata)
{
    gsDofMapper a = rtAnisotropicMapper();   // 1 patch, concatenated, distinct
    gsDofMapper b = raggedIdentityMapper();  // 3 patches, identity, not distinct

    a.swap(b);

    CHECK_EQUAL(3u, (unsigned)a.numPatches());
    CHECK(gsDofMapper::GlobalIdentity == a.layout());
    CHECK(!a.hasDistinctComponentSpaces());
    CHECK_EQUAL(7u,  (unsigned)a.totalSize(0));
    CHECK_EQUAL(10u, (unsigned)a.totalSize(1));

    CHECK_EQUAL(1u, (unsigned)b.numPatches());
    CHECK(gsDofMapper::PatchConcatenated == b.layout());
    CHECK(b.hasDistinctComponentSpaces());
    CHECK_EQUAL(28u, (unsigned)b.patchSize(0,0));
    CHECK_EQUAL(30u, (unsigned)b.patchSize(0,1));
}

// =========================================================================
// setIdentity() as a reset of an already-populated mapper
// =========================================================================

// setIdentity() rebuilds the mapping, the counts and the layout, so it must
// also drop the tag list: its entries are global indices of the numbering
// being thrown away.  Left behind, they survive into a numbering that does
// not contain them, and taggedSize()/getTagged()/is_tagged_index() report
// dofs that do not exist.
TEST(set_identity_clears_stale_tags)
{
    gsDofMapper m = twoPatchCoupledElim();
    m.markCoupledAsTagged();
    CHECK(m.taggedSize() > 0);
    const index_t staleTag = m.getTagged().back();

    m.setIdentity(1, 3, 1);
    m.finalize();

    CHECK_EQUAL(0, m.taggedSize());
    CHECK(m.getTagged().empty());
    CHECK_EQUAL(3, m.size());
    // The stale tag was an index of the discarded numbering; nothing in the
    // new one may answer to it.
    for (index_t gl = 0; gl != m.size(); ++gl)
        CHECK(!m.is_tagged_index(gl));
    if (staleTag < m.size())
        CHECK(!m.is_tagged_index(staleTag));
}

// Re-initialising a populated mapper with a smaller shape must leave nothing
// of the old one behind -- the reason every initialiser assigns rather than
// resizes.
TEST(set_identity_reinitializes_completely)
{
    gsDofMapper m = threeCompUniform();
    CHECK_EQUAL(3, m.numComponents());

    std::vector<size_t> dofs(2);
    dofs[0] = 4; dofs[1] = 6;
    m.setIdentity(2, dofs);
    m.finalize();

    CHECK_EQUAL(2, m.numComponents());
    CHECK_EQUAL(2u, (unsigned)m.numPatches());
    CHECK(gsDofMapper::GlobalIdentity == m.layout());
    CHECK(!m.hasDistinctComponentSpaces());
    CHECK_EQUAL(4u, (unsigned)m.totalSize(0));
    CHECK_EQUAL(6u, (unsigned)m.totalSize(1));
    CHECK_EQUAL(10u, (unsigned)m.mapSize());
    CHECK_EQUAL(10, m.size());
    CHECK_EQUAL(0, m.boundarySize());
    CHECK(!m.usableByUniformEvaluator()); // ragged identity totals
}

// =========================================================================
// Construction-time validation
// =========================================================================

TEST(ragged_constructor_rejects_invalid_metadata)
{
    // No components at all.
    CHECK_THROW(gsDofMapper(std::vector<gsVector<index_t> >(), false),
                std::runtime_error);

    // No patches.
    {
        std::vector<gsVector<index_t> > sz(1);
        CHECK_THROW(gsDofMapper(sz, false), std::runtime_error);
    }

    // Components disagreeing about the patch count: ragged means different
    // sizes per (component,patch), never different patch sets.
    {
        std::vector<gsVector<index_t> > sz(2);
        sz[0].resize(2); sz[0][0] = 3; sz[0][1] = 3;
        sz[1].resize(3); sz[1][0] = 3; sz[1][1] = 3; sz[1][2] = 3;
        CHECK_THROW(gsDofMapper(sz, false), std::runtime_error);
    }

    // Negative patch size.
    {
        std::vector<gsVector<index_t> > sz(1);
        sz[0].resize(2); sz[0][0] = 3; sz[0][1] = -1;
        CHECK_THROW(gsDofMapper(sz, false), std::runtime_error);
    }
}

TEST(set_identity_rejects_invalid_metadata)
{
    gsDofMapper m;
    CHECK_THROW(m.setIdentity(0, 5, 1), std::runtime_error);   // no patches
    CHECK_THROW(m.setIdentity(-1, 5, 1), std::runtime_error);  // no patches
    CHECK_THROW(m.setIdentity(1, 5, 0), std::runtime_error);   // no components
    CHECK_THROW(m.setIdentity(1, std::vector<size_t>()), std::runtime_error);
}

// Dof counts are stored, and accumulated across components by finalize(), in
// index_t -- a build-time configurable type that is plain int by default and
// may be far narrower than size_t.  A count that overflows it must be
// rejected against index_t's range, and -- this is the operative part --
// BEFORE anything is allocated or narrowed: validating after the fact would
// mean either a wrapped negative count or a multi-gigabyte allocation on the
// way to the diagnostic.  Every case below therefore must throw without the
// mapper ever sizing its storage.
TEST(construction_rejects_counts_beyond_index_range)
{
    const size_t imax = static_cast<size_t>(std::numeric_limits<index_t>::max());

    // Cumulative over patches (one component).
    {
        gsVector<index_t> sz(2);
        sz[0] = std::numeric_limits<index_t>::max();
        sz[1] = std::numeric_limits<index_t>::max();
        CHECK_THROW(gsDofMapper(sz, 1), std::runtime_error);
    }

    // Cumulative over components: each component fits on its own, their sum
    // does not.  This is the case a per-component-only check misses.
    {
        gsVector<index_t> sz(1);
        sz[0] = static_cast<index_t>(imax/2 + 1);
        CHECK_THROW(gsDofMapper(sz, 2), std::runtime_error);
    }

    // Same, through the ragged constructor.
    {
        std::vector<gsVector<index_t> > sz(2);
        sz[0].resize(1); sz[0][0] = static_cast<index_t>(imax/2 + 1);
        sz[1].resize(1); sz[1][0] = static_cast<index_t>(imax/2 + 1);
        CHECK_THROW(gsDofMapper(sz, false), std::runtime_error);
    }

    // setIdentity takes size_t counts, so a single component can exceed
    // index_t's range on its own.  Only meaningful where index_t is no wider
    // than size_t, which is every supported configuration.
    if (sizeof(index_t) <= sizeof(size_t))
    {
        gsDofMapper m;
        CHECK_THROW(m.setIdentity(1, std::vector<size_t>(1, imax + 1)),
                    std::runtime_error);

        std::vector<size_t> dofs(2);
        dofs[0] = imax; dofs[1] = 1;    // each fits, the sum does not
        CHECK_THROW(m.setIdentity(1, dofs), std::runtime_error);
    }
}


// =========================================================================
// Per-component prefix queries
// =========================================================================
//
// After finalize() the per-component count vectors m_numFreeDofs,
// m_numElimDofs and m_numCpldDofs are CUMULATIVE prefix sums, so a
// component's own count is always a prefix difference.  Reading a prefix
// where a difference is meant, or the last component's prefix where the
// queried component's is meant, is correct for component 0 and for a
// single-component mapper and wrong everywhere else -- which is why every
// test below needs a fixture with three components and asserts on the
// components >= 1.
//
// F3 (threeCompUniform) has, per component:
//
//   component | local storage per patch          | free | cpld | elim
//   ----------+----------------------------------+------+------+-----
//       0     | [20,0,1,6]  [6,2,3,4,5]          |   7  |   1  |  1
//       1     | [21,7,10,11] [8,10,11,9,22]      |   5  |   2  |  2
//       2     | [12,13,14,15] [16,17,18,23,19]   |   8  |   0  |  1
//
// so the free blocks are [0,7), [7,12), [12,20), the coupled dofs sit at the
// top of each ({6}, {10,11}, {}) and the eliminated ones are 20, {21,22} and
// 23.  Every literal below is read off that table.

TEST(three_comp_coupled_queries_per_component)
{
    const gsDofMapper m = threeCompUniform();

    PIN("f3.coupled.c0",
        "flags=...C|C.... cidx=[0:3->0,1:0->0] gflags=......C...CC............"
        " findCoupled=[3],[0] findCoupledPairs=00[],01[3],10[0],11[]"
        " findFreeUncoupled=[1,2],[1,2,3,4]",
        dumpCoupledQueries(m, 0));

    PIN("f3.coupled.c1",
        "flags=..CC|.CC.. cidx=[0:2->1,0:3->2,1:1->1,1:2->2]"
        " gflags=......C...CC............"
        " findCoupled=[2,3],[1,2] findCoupledPairs=00[],01[2,3],10[1,2],11[]"
        " findFreeUncoupled=[1],[0,3]",
        dumpCoupledQueries(m, 1));

    PIN("f3.coupled.c2",
        "flags=....|..... cidx=[] gflags=......C...CC............"
        " findCoupled=[],[] findCoupledPairs=00[],01[],10[],11[]"
        " findFreeUncoupled=[0,1,2,3],[0,1,2,4]",
        dumpCoupledQueries(m, 2));
}

// is_coupled_index, on its own and over the whole global range: exactly the
// three dofs that really are shared between the two patches, and nothing
// else.  Taking the cumulative m_numCpldDofs[c+1] as the band width instead
// of the component's own count widens component 1's band by component 0's
// one coupled dof and component 2's by all three, so free-uncoupled dofs of
// the later components are reported coupled.
TEST(is_coupled_index_uses_the_component_own_coupled_count)
{
    const gsDofMapper m = threeCompUniform();

    // Derived independently of the mapper's own bands: a coupled dof is a
    // free dof with more than one pre-image.
    std::vector<std::pair<index_t,index_t> > pre;
    for (index_t gl = 0; gl != m.size(); ++gl)
    {
        m.preImage(gl, pre);
        const bool shared = m.is_free_index(gl) && pre.size() > 1;
        CHECK_EQUAL(shared, m.is_coupled_index(gl));
    }

    CHECK_EQUAL(3, m.coupledSize());
}

TEST(three_comp_find_boundary_free_per_component)
{
    const gsDofMapper m = threeCompUniform();
    PIN("f3.findbf.c0", "bnd=[0],[] free=[1,2,3],[0,1,2,3,4]",   dumpFindBoundaryFree(m, 0));
    PIN("f3.findbf.c1", "bnd=[0],[4] free=[1,2,3],[0,1,2,3]",    dumpFindBoundaryFree(m, 1));
    PIN("f3.findbf.c2", "bnd=[],[3] free=[0,1,2,3],[0,1,2,4]",   dumpFindBoundaryFree(m, 2));
}

// =========================================================================
// firstIndex(c)
// =========================================================================

// firstIndex(c) is the smallest global index component c owns.  Checked
// against the minimum actually taken by index(i,k,c), which is an
// independent oracle: it never consults the count vectors.
namespace {
void checkFirstIndexAgainstMinimum(const gsDofMapper & m)
{
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        index_t least = -1;
        for (index_t k = 0; k != nPatches(m); ++k)
        {
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            for (index_t i = 0; i != n; ++i)
            {
                const index_t gl = m.index(i, k, c);
                if (least < 0 || gl < least) least = gl;
            }
        }
        // A component with no local dof at all has no index to compare
        // against; first_index_of_an_empty_component pins that case.
        if (least >= 0)
            CHECK_EQUAL(least, m.firstIndex(c));
    }
}
} // anonymous namespace

TEST(first_index_is_the_smallest_index_of_the_component)
{
    checkFirstIndexAgainstMinimum(threeCompUniform());
    checkFirstIndexAgainstMinimum(threeCompShifted());
    checkFirstIndexAgainstMinimum(identityMapper());
    checkFirstIndexAgainstMinimum(raggedPatchMapper());

    // The literals for F3: the free block starts, since every component has
    // free dofs.  m_numFreeDofs[c]+m_numElimDofs[c] -- the pre-renumbering
    // base -- overshoots them by the eliminated dofs of the earlier
    // components once finalize() has moved the eliminated blocks above all
    // the free ones.
    const gsDofMapper m = threeCompUniform();
    CHECK_EQUAL(0,  m.firstIndex(0));
    CHECK_EQUAL(7,  m.firstIndex(1));
    CHECK_EQUAL(12, m.firstIndex(2));
}

// A component that owns no dof at all has no index to report.  It must not
// be confused with an eliminated-only component: "no free dof" alone is not
// evidence of an eliminated block, and answering with the eliminated-block
// start pushes an empty component past the whole free range.
TEST(first_index_of_an_empty_component)
{
    std::vector<gsVector<index_t> > sz(3);
    sz[0].resize(1); sz[0][0] = 2;
    sz[1].resize(1); sz[1][0] = 0;   // empty component
    sz[2].resize(1); sz[2][0] = 3;
    gsDofMapper m(sz, /*hasDistinctComponentSpaces=*/false);
    m.finalize();

    CHECK_EQUAL(5, m.size());
    CHECK_EQUAL(5, m.freeSize());
    CHECK_EQUAL(0, m.boundarySize());
    CHECK_EQUAL(0, m.size(1));

    CHECK_EQUAL(0, m.firstIndex(0));
    CHECK_EQUAL(2, m.firstIndex(1));   // the start of its (empty) free block
    CHECK_EQUAL(2, m.firstIndex(2));
    checkFirstIndexAgainstMinimum(m);
}

// A component whose dofs are all eliminated owns no free index at all, so
// its smallest index is the start of its eliminated block -- which lies
// above every component's free block.
TEST(first_index_of_an_eliminated_only_component)
{
    gsVector<index_t> sz(1);
    sz[0] = 3;
    gsDofMapper m(sz, 2);
    for (index_t i = 0; i != 3; ++i)
        m.eliminateDof(i, 0, 0);
    m.finalize();

    CHECK_EQUAL(3, m.freeSize());
    CHECK_EQUAL(3, m.boundarySize());
    CHECK_EQUAL(0, m.freeSize(0));
    checkFirstIndexAgainstMinimum(m);

    CHECK_EQUAL(3, m.firstIndex(0));   // its eliminated block
    CHECK_EQUAL(0, m.firstIndex(1));   // its free block
}

// =========================================================================
// inverseAsVector(c)
// =========================================================================

// The inverse of asVector(c) over the whole global index space: every
// position that is not the image of a local dof of component c carries the
// -1 sentinel instead of whatever the allocation happened to hold.
TEST(inverse_as_vector_marks_other_components)
{
    gsVector<index_t> sz(2);
    sz[0] = 3; sz[1] = 4;
    gsDofMapper m(sz, 2);
    m.finalize();
    CHECK(m.isPermutation());

    PIN("inv.c0", "[0,1,2,3,4,5,6,-1,-1,-1,-1,-1,-1,-1]", join(m.inverseAsVector(0)));
    PIN("inv.c1", "[-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6]", join(m.inverseAsVector(1)));

    // It really is the inverse of asVector on the component's own block.
    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        const gsVector<index_t> fwd = m.asVector(c);
        const gsVector<index_t> inv = m.inverseAsVector(c);
        CHECK_EQUAL(m.size(), inv.size());
        for (index_t j = 0; j != fwd.size(); ++j)
            CHECK_EQUAL(j, inv[fwd[j]]);
    }
}

// =========================================================================
// inverseOnPatch(k)
// =========================================================================

// The inverse on a patch covers exactly the dofs that live on that patch,
// in every component.  Iterating a whole component vector from the patch
// offset instead attributes the following patches' dofs to the requested
// one and, for every patch but the first, reads past the end of the vector.
TEST(inverse_on_patch_is_bounded_to_the_patch)
{
    const gsDofMapper m = threeCompUniform();

    PIN("f3.inverseonpatch.k0",
        "[(0,1),(1,2),(6,3),(7,1),(10,2),(11,3),(12,0),(13,1),(14,2),(15,3),(20,0),(21,0)]",
        dumpInverseOnPatch(m, 0));
    PIN("f3.inverseonpatch.k1",
        "[(2,1),(3,2),(4,3),(5,4),(6,0),(8,0),(9,3),(10,1),(11,2),(16,0),(17,1),(18,2),(19,4),(22,4),(23,3)]",
        dumpInverseOnPatch(m, 1));

    // Independent oracle: the result is exactly { index(i,k,c) -> i }.
    for (index_t k = 0; k != nPatches(m); ++k)
    {
        const std::map<index_t,index_t> inv = m.inverseOnPatch(k);
        size_t expected = 0;
        for (index_t c = 0; c != m.numComponents(); ++c)
        {
            const index_t n = static_cast<index_t>(m.patchSize(k, c));
            expected += n;
            for (index_t i = 0; i != n; ++i)
            {
                const std::map<index_t,index_t>::const_iterator it =
                    inv.find(m.index(i, k, c));
                CHECK(it != inv.end());
                if (it != inv.end()) CHECK_EQUAL(i, it->second);
            }
        }
        // Coupled dofs appear once per local dof they carry on this patch,
        // so the map may be smaller than the total, never larger.
        CHECK(inv.size() <= expected);
    }
}

// Under the aliased layout every patch carries the complete inverse, so all
// patches return identical contents.
TEST(inverse_on_patch_is_aliased_under_global_identity)
{
    const gsDofMapper m = raggedIdentityMapper();
    const std::string k0 = dumpInverseOnPatch(m, 0);
    for (index_t k = 1; k != nPatches(m); ++k)
        PIN("f10.inverseonpatch", k0, dumpInverseOnPatch(m, k));
    CHECK_EQUAL(static_cast<size_t>(m.size()), m.inverseOnPatch(0).size());
}

// =========================================================================
// anyPreImages(c)
// =========================================================================

// anyPreImages indexes its result by the global dof value, which for every
// component but the first is larger than that component's own storage size:
// sizing the result by that storage size is an out-of-bounds write, not
// merely a wrong answer, and could not be exercised at all before.
TEST(any_pre_images_agrees_with_any_pre_image)
{
    const gsDofMapper m = threeCompUniform();

    for (index_t c = 0; c != m.numComponents(); ++c)
    {
        const std::vector<std::pair<index_t,index_t> > all = m.anyPreImages(c);
        CHECK(all.size() >= static_cast<size_t>(m.size()));

        for (index_t gl = 0; gl != m.size(); ++gl)
        {
            if (m.componentOf(gl) == c)
                CHECK(m.anyPreImage(gl) == all[gl]);
            else
                CHECK_EQUAL(-1, all[gl].first);   // not in this component
        }
    }
}

// =========================================================================
// permuteFreeDofs(permutation, c)
// =========================================================================

// The permutation is component-local: it has one entry per free dof of the
// component it is applied to, and it may not move an index out of that
// component's free block.  Taking its length from the cumulative
// m_numFreeDofs[c+1] both demands a longer permutation than the component
// has free dofs and, indexed by an unrebased global index, would permute
// component c's dofs into its predecessors' bands.
TEST(permute_free_dofs_is_component_local)
{
    gsDofMapper m = threeCompUniform();
    CHECK_EQUAL(5, m.freeSize(1));

    gsVector<index_t> perm(5);
    perm << 4, 3, 2, 1, 0;
    m.permuteFreeDofs(perm, 1);

    // Component 1's free block is [7,12): every free index stays inside it,
    // and the two eliminated dofs (21 and 22) are untouched.
    PIN("perm.c1", "[21,11,8,7,10,8,7,9,22]", join(m.asVector(1)));

    // The other components are not touched at all.
    PIN("perm.c0", "[20,0,1,6,6,2,3,4,5]",          join(m.asVector(0)));
    PIN("perm.c2", "[12,13,14,15,16,17,18,23,19]",  join(m.asVector(2)));

    // Permuting a component destroys the tracking of ITS coupled dofs only;
    // component 0's single coupled dof is still counted.
    CHECK_EQUAL(1, m.coupledSize());
}

// markCoupledAsTagged tags the top of each component's own free block, which
// is where finalize() puts that component's coupled dofs.  Taking the band
// start from m_numFreeDofs[c+1]+m_numElimDofs[c] instead walks off the
// coupled dofs entirely -- the eliminated blocks are stacked above every
// component's free block, not interleaved with them -- and taking the band
// WIDTH from the cumulative m_numCpldDofs[c+1] then overruns, for the last
// component past size() itself.
TEST(mark_coupled_as_tagged_tags_the_coupled_dofs)
{
    gsDofMapper m = threeCompUniform();
    CHECK_EQUAL(0, m.taggedSize());       // nothing tagged beforehand
    m.markCoupledAsTagged();

    PIN("tagcpld.f3", "[6,10,11]", join(m.getTagged()));
    CHECK_EQUAL(m.coupledSize(), m.taggedSize());

    // The tagged set is now exactly the coupled set, component by component.
    for (index_t gl = 0; gl != m.size(); ++gl)
        CHECK_EQUAL(m.is_coupled_index(gl), m.is_tagged_index(gl));

    // Single component, one collapsed group: the one coupled dof, and it is
    // a valid index -- the old band start, 8, was size() itself.
    gsDofMapper c = collapsedMapper();
    c.markCoupledAsTagged();
    PIN("tagcpld.f7", "[7]", join(c.getTagged()));
    CHECK(c.getTagged().back() < c.size());
}

// The coupled dofs are added to whatever is already tagged, not substituted
// for it.
TEST(mark_coupled_as_tagged_keeps_existing_tags)
{
    gsDofMapper m = twoPatchCoupledElim();   // markTagged'd dofs 0 and 3
    PIN("tagcpld.before", "[0,3]", join(m.getTagged()));
    m.markCoupledAsTagged();
    PIN("tagcpld.after", "[0,3,5,6]", join(m.getTagged()));
}

// A component-local permutation moves only the tags that lie in that
// component's free block.  Rebuilding the tag list from the permuted
// component's storage -- which is the only storage the permutation walks --
// visits no other component, so every tag of every other component is
// silently deleted.  That breaks the documented "markCoupledAsTagged(), then
// permute, then use the tagged queries" workflow, which is the whole reason
// permuting is allowed to destroy the coupled bookkeeping in the first place.
TEST(permute_free_dofs_keeps_other_components_tags)
{
    gsDofMapper m = threeCompUniform();

    m.markTagged(1, 0, 0);   // component 0, global 0
    m.markTagged(1, 0, 1);   // component 1, global 7  -- the permuted one
    m.markTagged(1, 0, 2);   // component 2, global 13
    PIN("permtag.before", "[0,7,13]", join(m.getTagged()));

    gsVector<index_t> perm(5);
    perm << 4, 3, 2, 1, 0;
    m.permuteFreeDofs(perm, 1);

    // Component 1's free block is [7,12), so its tag 7 becomes 7+perm[0]==11.
    // The other two are outside the block and must be untouched.
    PIN("permtag.after", "[0,11,13]", join(m.getTagged()));
    CHECK_EQUAL(3, m.taggedSize());
    CHECK(m.is_tagged_index(0));
    CHECK(m.is_tagged_index(11));
    CHECK(m.is_tagged_index(13));
    CHECK(!m.is_tagged_index(7));
}

// An eliminated dof's tag is not in any free block, so it survives a
// permutation of its own component unchanged.
TEST(permute_free_dofs_keeps_eliminated_tags)
{
    gsDofMapper m = threeCompUniform();
    m.markTagged(0, 0, 0);   // component 0's eliminated dof, global 20

    gsVector<index_t> perm(7);
    perm << 3, 0, 6, 1, 5, 2, 4;
    m.permuteFreeDofs(perm, 0);

    PIN("permtag.elim", "[20]", join(m.getTagged()));
}

}
