# A nushell script that run the frog_fitfunc binary for a number of different function, fitting them for error analysis.
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/lagrange/" --function "(x^2 - y^2)/4" --errors "errors/fit_quadrangular_quadratic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/lagrange/" --function "(x^2 - y^2)/4" --errors "errors/fit_quadrangular_quadratic_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/lagrange/" --function "(x^3 - y^3)/16" --errors "errors/fit_quadrangular_cubic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/lagrange/" --function "(x^3 - y^3)/16" --errors "errors/fit_quadrangular_cubic_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/lagrange/" --function "(x^4 - y^4)/64" --errors "errors/fit_quadrangular_quartic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/lagrange/" --function "(x^4 - y^4)/64" --errors "errors/fit_quadrangular_quartic_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/lagrange/" --function "sin(x) * cos(y)" --errors "errors/fit_quadrangular_trig_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/lagrange/" --function "sin(x) * cos(y)" --errors "errors/fit_quadrangular_trig_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/lagrange/" --function "(53 x^3 + 90 x^2 * y + 13 y^2 * x + 80 y^3 + 44 x^2 + 94 x * y + 11 y^2 + 21 x + 41 y + 62)/1600" --errors "errors/fit_quadrangular_random_cubic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/lagrange/" --function "(53 x^3 + 90 x^2 * y + 13 y^2 * x + 80 y^3 + 44 x^2 + 94 x * y + 11 y^2 + 21 x + 41 y + 62)/1600" --errors "errors/fit_quadrangular_random_cubic_5.csv"
