# A nushell script that run the frog_fitfunc binary for a number of different function, fitting them for error analysis.
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "(x^4 - y^4)/64" --errors "errors/fit_quadrangular_quartic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "(x^4 - y^4)/64" --errors "errors/fit_quadrangular_quartic_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "(x^3 - y^3)/16" --errors "errors/fit_quadrangular_cubic_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "(x^3 - y^3)/16" --errors "errors/fit_quadrangular_cubic_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "sin(x) * cos(y)" --errors "errors/fit_quadrangular_trig_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "sin(x) * cos(y)" --errors "errors/fit_quadrangular_trig_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "x * x * x" --errors "errors/fit_quadrangular_cubic_xxx_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "x * x * x" --errors "errors/fit_quadrangular_cubic_xxx_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "x * x * y" --errors "errors/fit_quadrangular_cubic_xxy_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "x * x * y" --errors "errors/fit_quadrangular_cubic_xxy_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "x * y * y" --errors "errors/fit_quadrangular_cubic_xyy_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "x * y * y" --errors "errors/fit_quadrangular_cubic_xyy_5.csv"
./bin/frog_fitfunc --paraview --cnet --valence 3 --steps 4 --frogdir "frog/quad/" --function "y * y * y" --errors "errors/fit_quadrangular_cubic_yyy_3.csv"
./bin/frog_fitfunc --paraview --cnet --valence 5 --steps 4 --frogdir "frog/quad/" --function "y * y * y" --errors "errors/fit_quadrangular_cubic_yyy_5.csv"
