name: Response bot

on:
  - pull_request

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.pull_request.node_id }}
        response: "Thank you for opening your Pull Request !\nIn the next 30 minutes several tests will run. The detailed reports will be available at:\nhttps://cdash-ci.irisa.fr/index.php?project=Gismo&filtercount=1&showfilters=1&field1=buildname&compare1=66&value1=[${{ github.event.number }}]"
        author: ${{ github.event.pull_request.user.login }}
