name: Auto message for PR's and Issues
on: [pull_request] #issues
jobs:
  build:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Thank you for opening your Pull Request !\nIn the next 30 minutes several tests will run. The detailed reports will be available at:\nhttps://cdash-ci.irisa.fr/index.php?project=Gismo&filtercount=1&showfilters=1&field1=buildname&compare1=66&value1=[${{ github.event.number }}]"
