name: build_python_wheels

on:
  push:
    branches: ["dev"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # Build wheels for pull requests to ensure that the build process works and that the resulting wheels are valid. This is a quick check to catch issues early.
  linux_test_wheel:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_ENVIRONMENT: "GITHUB_ACTIONS=True"
        CIBW_ARCHS: "x86_64"
        CIBW_BUILD: "cp312-manylinux_x86_64"
        CIBW_SKIP: "cp3??t-*"
        # Use a wildcard to capture the build directory for ANY python version
        # and include BOTH the lib folder (for gismo) and the build root (for nanobind-gismo)
        CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /project/build -name "*.so*" -exec dirname {} \; | sort -u | tr '\n' ':')
          auditwheel repair -w {dest_dir} {wheel}

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-linux_wheel_x86_64
        path: ./wheelhouse/*.whl
        overwrite: true

  linux_wheel:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v3.3.1
      env:
        CIBW_ENVIRONMENT: "GITHUB_ACTIONS=True"
        CIBW_ARCHS: "x86_64"
        CIBW_BUILD: "cp*manylinux*"
        CIBW_SKIP: "cp3??t-*"
        # Use a wildcard to capture the build directory for ANY python version
        # and include BOTH the lib folder (for gismo) and the build root (for nanobind-gismo)
        CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /project/build -name "*.so*" -exec dirname {} \; | sort -u | tr '\n' ':')
          auditwheel repair -w {dest_dir} {wheel}

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-linux_wheel_x86_64
        path: ./wheelhouse/*.whl
        overwrite: true

  macos_wheel:
    runs-on: macos-latest
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        arch: [x86_64, arm64]
        cw_build: ["cp*"]
        exclude:
          - arch: arm64
            cw_build: "pp*"

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v3.3.1
      env:
         CIBW_ENVIRONMENT: "GITHUB_ACTIONS=True"
         CIBW_ARCHS: ${{ matrix.arch }}
         CIBW_BUILD: ${{ matrix.cw_build }}
         CIBW_TEST_SKIP: "*-macosx_arm64"
         CIBW_SKIP: "cp3??t-*"

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-macos_wheel_${{ matrix.arch }}
        path: ./wheelhouse/*.whl
        overwrite: true

  linux_wheel_qemu:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, ppc64le]
        cw_build: ["cp38*many*", "cp39*many*", "cp310*many*", "cp311*many*", "cp312*many*", "cp313*many*", "cp314*many*"]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: build wheels
      uses: pypa/cibuildwheel@v3.3.1
      env:
         CIBW_ENVIRONMENT: "GITHUB_ACTIONS=True"
         CIBW_ARCHS: ${{ matrix.arch }}
         CIBW_BUILD: ${{ matrix.cw_build }}
         CIBW_TEST_SKIP: "*-*linux_aarch64"

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-linux_wheel_qemu_${{ matrix.arch }}_${{ matrix.cw_build }}
        path: ./wheelhouse/*.whl
        overwrite: true

  source_dist:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build sdist
      run: pipx run build --sdist .

    - uses: actions/upload-artifact@v4
      with:
         name: artifact-source_dist
         path: ./dist/*
         overwrite: true

  upload_pypi:
    needs: [macos_wheel, linux_wheel, linux_wheel_qemu, source_dist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
