on:
  push:
    branches:
      - release
#    tags:
#      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
#      working-directory: ${{runner.workspace}}
      - name: Checkout G+Smo
        uses: actions/checkout@v3
      - name: Create tag
        shell: bash
        run: |
          export TAGVER=$(grep "https://github.com/gismo/gismo/releases/tag/v" changelog | awk '{print $1;}' | tail -1)        
          git tag $TAGVER
          git push origin $TAGVER
          export CLOG=$(sed -n -e '/$TAGVER/,$p' changelog)
          echo $CLOG
#          export GIT_COMMIT=$(git -C gismo rev-parse --short "$GITHUB_SHA")
      - name: Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            $CLOD
          draft: false
          prerelease: true
